package be.steby.CoreProject.bll.domains.auth.models;

/**
 * Business logic layer request for TOTP two-factor authentication activation verification.
 *
 * This record contains all necessary data for the business logic layer to process
 * a TOTP 2FA activation verification request (step 2 of the setup flow).
 *
 * The business logic will:
 * 1. Validate the JWT activation token and extract claims (including hashed secret)
 * 2. Verify the provided TOTP code against the secret from the token
 * 3. Activate TOTP 2FA for the user if verification succeeds
 *
 * Note: The verification code is generated by the user's authenticator app using
 * the secret they scanned/entered in step 1. This proves they have correctly
 * configured their authenticator app before we persist the TOTP configuration.
 *
 * @param verificationCode the 6-digit TOTP code from the user's authenticator app
 * @param activationToken the JWT token containing hashed secret and user info
 *
 * @author Steby Team
 * @since 2.0.0
 */
public record TotpTwoFactorActivationBllRequest(
        String verificationCode,
        String activationToken
) {

    /**
     * Validates the request parameters during record construction.
     *
     * @throws IllegalArgumentException if any parameter is null, blank, or invalid format
     */
    public TotpTwoFactorActivationBllRequest {
        if (verificationCode == null || verificationCode.isBlank()) {
            throw new IllegalArgumentException("Verification code cannot be null or blank");
        }

        if (activationToken == null || activationToken.isBlank()) {
            throw new IllegalArgumentException("Activation token cannot be null or blank");
        }

        String trimmedCode = verificationCode.trim();
        if (!trimmedCode.matches("\\d{6}")) {
            throw new IllegalArgumentException("Verification code must be exactly 6 digits");
        }
    }

    /**
     * Returns the verification code with whitespace trimmed.
     *
     * @return trimmed verification code
     */
    public String getTrimmedVerificationCode() {
        return verificationCode.trim();
    }
}