package be.steby.CoreProject.bll.domains.crm.commercialaction.exceptions;

import be.steby.CoreProject.dl.enums.crm.CommercialActionStatus;

/**
 * Exception thrown when an operation is attempted on a commercial action that has already
 * reached a terminal state ({@code DONE} or {@code CANCELLED}).
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Attempting to complete an action that is already done or cancelled</li>
 *   <li>Attempting to cancel an action that is already done or cancelled</li>
 *   <li>Attempting to update an action in a terminal state</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see CommercialActionDomainException
 */
public class CommercialActionAlreadyTerminatedException extends CommercialActionDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "COMMERCIAL_ACTION_ALREADY_TERMINATED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public CommercialActionAlreadyTerminatedException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public CommercialActionAlreadyTerminatedException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public CommercialActionAlreadyTerminatedException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public CommercialActionAlreadyTerminatedException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception indicating a commercial action is already in a terminal state.
     *
     * @param publicId      the public UUID of the terminated action
     * @param currentStatus the current terminal status of the action
     * @return a new CommercialActionAlreadyTerminatedException
     */
    public static CommercialActionAlreadyTerminatedException forAction(String publicId,
                                                                        CommercialActionStatus currentStatus) {
        return new CommercialActionAlreadyTerminatedException(
                "CommercialAction is already " + currentStatus + ": " + publicId);
    }
}
