#!/usr/bin/env python3
"""
Adds ERROR_CODE constant + getErrorCode() override to every class that
extends CoreProjectException (directly or indirectly).

The error code is derived from the class name:
  InvalidAccessTokenException  →  INVALID_ACCESS_TOKEN
  TwoFactorCodeDeliveryException  →  TWO_FACTOR_CODE_DELIVERY

Usage:
  python add_error_codes.py <src_root>           # live run
  python add_error_codes.py <src_root> --dry-run # preview only
"""

import re
import sys
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────────────────────

ROOT_EXCEPTION = "CoreProjectException"

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def to_upper_snake(class_name: str) -> str:
    """
    InvalidAccessTokenException  →  INVALID_ACCESS_TOKEN
    GpxAlreadyImportedException  →  GPX_ALREADY_IMPORTED
    """
    name = re.sub(r"Exception$", "", class_name)            # strip suffix
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)    # camel split
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name) # e.g. GPXFile → GPX_File
    return name.upper()


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def extract_class_info(content: str) -> tuple[str | None, str | None]:
    """Returns (class_name, parent_name) or (None, None)."""
    m = re.search(
        r"(?:public\s+)?(?:abstract\s+)?class\s+(\w+)\s+extends\s+(\w+)",
        content
    )
    return (m.group(1), m.group(2)) if m else (None, None)


def is_already_patched(content: str) -> bool:
    return "ERROR_CODE" in content or "getErrorCode()" in content


# ──────────────────────────────────────────────────────────────────────────────
# Hierarchy builder
# ──────────────────────────────────────────────────────────────────────────────

def build_hierarchy(java_files: list[Path]) -> dict[str, set[str]]:
    """
    Returns a map of class_name → set of direct children,
    and separately a flat set of all descendants of ROOT_EXCEPTION.
    """
    parents: dict[str, str] = {}   # child → parent

    for f in java_files:
        cls, parent = extract_class_info(read(f))
        if cls and parent:
            parents[cls] = parent

    # BFS from root
    descendants: set[str] = set()
    queue = [ROOT_EXCEPTION]
    while queue:
        current = queue.pop()
        for cls, par in parents.items():
            if par == current and cls not in descendants:
                descendants.add(cls)
                queue.append(cls)

    return descendants


# ──────────────────────────────────────────────────────────────────────────────
# File patching
# ──────────────────────────────────────────────────────────────────────────────

def build_patch(class_name: str) -> str:
    code = to_upper_snake(class_name)
    return (
        f"\n"
        f"    // ── auto-generated by add_error_codes.py ──────────────────────\n"
        f"    private static final String ERROR_CODE = \"{code}\";\n"
        f"\n"
        f"    @Override\n"
        f"    public String getErrorCode() {{\n"
        f"        return ERROR_CODE;\n"
        f"    }}\n"
        f"    // ────────────────────────────────────────────────────────────────\n"
    )


def find_class_body_start(content: str, class_name: str) -> int | None:
    """Returns the index just after the opening brace of the class body."""
    m = re.search(
        rf"class\s+{re.escape(class_name)}[^{{]*\{{", content, re.DOTALL
    )
    return m.end() if m else None


def find_insertion_point(content: str, class_name: str) -> int | None:
    """
    Returns the index at which to insert the patch block.
    Strategy: just before the first constructor declaration (and its Javadoc),
    but NEVER before the class opening brace.
    Fallback: right after the opening brace of the class body.
    """
    class_body_start = find_class_body_start(content, class_name)
    if class_body_start is None:
        return None

    # Look for first constructor INSIDE the class body only
    ctor_re = re.compile(
        rf"\n([ \t]+(?:public|protected)\s+{re.escape(class_name)}\s*\()",
        re.MULTILINE
    )
    m = ctor_re.search(content, class_body_start)
    if m:
        # Walk back to swallow any preceding Javadoc, but not past class_body_start
        before = content[class_body_start:m.start()]
        javadoc_re = re.compile(r"(/\*\*.*?\*/\s*)$", re.DOTALL)
        jm = javadoc_re.search(before)
        if jm:
            # position = class_body_start + start of the javadoc in before
            return class_body_start + jm.start()
        return m.start() + 1  # +1 to keep the leading newline

    # Fallback: right after opening brace
    return class_body_start


def patch_file(path: Path, class_name: str, dry_run: bool) -> bool:
    content = read(path)

    if is_already_patched(content):
        print(f"  [SKIP] {class_name:<50} already patched")
        return False

    pos = find_insertion_point(content, class_name)
    if pos is None:
        print(f"  [WARN] {class_name:<50} insertion point not found — skipped")
        return False

    patch = build_patch(class_name)
    new_content = content[:pos] + patch + content[pos:]
    code = to_upper_snake(class_name)

    if dry_run:
        print(f"  [DRY]  {class_name:<50}  →  {code}")
    else:
        write(path, new_content)
        print(f"  [OK]   {class_name:<50}  →  {code}")

    return True


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(1)

    src_root = Path(args[0])
    dry_run  = "--dry-run" in args

    if not src_root.exists():
        print(f"Error: '{src_root}' does not exist.")
        sys.exit(1)

    print(f"{'[DRY RUN] ' if dry_run else ''}Scanning: {src_root.resolve()}\n")

    # ── 1. Collect all Java files ────────────────────────────────────────────
    java_files = list(src_root.rglob("*.java"))
    print(f"  Total Java files found : {len(java_files)}")

    # ── 2. Build hierarchy ───────────────────────────────────────────────────
    hierarchy = build_hierarchy(java_files)
    print(f"  Exceptions in hierarchy: {len(hierarchy)}\n")

    # ── 3. Map class name → file ─────────────────────────────────────────────
    class_to_file: dict[str, Path] = {}
    for f in java_files:
        cls, _ = extract_class_info(read(f))
        if cls:
            class_to_file[cls] = f

    # ── 4. Patch ─────────────────────────────────────────────────────────────
    patched = skipped = missing = 0
    for cls in sorted(hierarchy):
        if cls not in class_to_file:
            print(f"  [MISS] {cls:<50} file not found in scanned tree")
            missing += 1
            continue

        ok = patch_file(class_to_file[cls], cls, dry_run)
        if ok:
            patched += 1
        else:
            skipped += 1

    # ── 5. Summary ───────────────────────────────────────────────────────────
    print(f"\n{'─' * 60}")
    print(f"  {'[DRY RUN] ' if dry_run else ''}Patched : {patched}")
    print(f"  Skipped  : {skipped}  (already had errorCode)")
    print(f"  Missing  : {missing}  (file not indexed)")
    print(f"{'─' * 60}")
    if dry_run:
        print("\n  Re-run without --dry-run to apply changes.")


if __name__ == "__main__":
    main()