package be.steby.CoreProject.bll.domains.account.exceptions.deletion;

import be.steby.CoreProject.bll.domains.account.exceptions.AccountDomainException;

/**
 * Thrown when a user submits a GDPR deletion request while one is already
 * pending confirmation.
 */
public class DeletionAlreadyRequestedException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DELETION_ALREADY_REQUESTED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public DeletionAlreadyRequestedException(String message) {
        super(message, 409);
    }
}