package be.steby.CoreProject.bll.domains.account.exceptions.deletion;

import be.steby.CoreProject.bll.domains.account.exceptions.AccountDomainException;

/**
 * Thrown when a GDPR deletion confirmation token has passed its expiry date.
 *
 * <p>The user must submit a new deletion request to obtain a fresh token.
 *
 * <p>HTTP status: 498 (Token Expired).
 */
public class DeletionTokenExpiredException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DELETION_TOKEN_EXPIRED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public DeletionTokenExpiredException(String message) {
        super(message, 498);
    }
}