package be.steby.CoreProject.bll.domains.account.exceptions.reactivation;

import be.steby.CoreProject.bll.domains.account.exceptions.AccountDomainException;

public class ReactivationNotAllowedException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "REACTIVATION_NOT_ALLOWED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public ReactivationNotAllowedException(String message) {
        super(message, 403);
    }

    public ReactivationNotAllowedException(String message, int status) {
        super(message, status);
    }
}