package be.steby.CoreProject.bll.domains.crm.pipeline.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all pipeline domain-related exceptions.
 *
 * <p>This abstract class extends {@link CoreProjectException} to integrate
 * with the global exception handling system via {@code ControllerAdvisor}.</p>
 *
 * <p>All specific pipeline exceptions should extend this class to ensure
 * consistent error handling across the pipeline domain.</p>
 *
 * <h3>Exception hierarchy</h3>
 * <pre>
 * CoreProjectException
 * └── PipelineDomainException
 *     ├── PipelineNotFoundException
 *     ├── PipelineNameAlreadyExistsException
 *     ├── PipelineValidationException
 *     ├── PipelineHasActiveDealsException
 *     ├── PipelineStepNotFoundException
 *     └── PipelineStepValidationException
 * </pre>
 *
 * @see CoreProjectException
 * @see PipelineNotFoundException
 * @see PipelineNameAlreadyExistsException
 * @see PipelineValidationException
 * @see PipelineHasActiveDealsException
 * @see PipelineStepNotFoundException
 * @see PipelineStepValidationException
 */
public abstract class PipelineDomainException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new pipeline domain exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public PipelineDomainException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new pipeline domain exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineDomainException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new pipeline domain exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new pipeline domain exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}