package be.steby.CoreProject.bll.domains.account.exceptions.deactivation;

import be.steby.CoreProject.bll.domains.account.exceptions.AccountDomainException;

public class AccountAlreadyDeactivatedException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ACCOUNT_ALREADY_DEACTIVATED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AccountAlreadyDeactivatedException(String message) {
        super(message, 409);
    }
}
