package be.steby.CoreProject.bll.domains.account.exceptions.deactivation;

import be.steby.CoreProject.bll.domains.account.exceptions.AccountDomainException;

public class DeactivationTokenNotFoundException extends AccountDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEACTIVATION_TOKEN_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public DeactivationTokenNotFoundException(String message) {
        super(message, 404);
    }
}
