package be.steby.CoreProject.bll.domains.account.exceptions.deactivation;

import be.steby.CoreProject.bll.common.exceptions.TokenExpiredException;

public class DeactivationTokenExpiredException extends TokenExpiredException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEACTIVATION_TOKEN_EXPIRED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Constructs a new TokenExpiredException with the specified detail message.
     * The status code is set to 498 by default.
     */
    public DeactivationTokenExpiredException(String message) {
        super(message, 498);
    }

    /**
     * Constructs a new {@code DeactivationTokenExpiredException} with the specified detail message
     * and status code.
     *
     * @param message the detail message
     * @param status the HTTP status code
     */
    public DeactivationTokenExpiredException(String message, int status) {
        super(message, status);
    }
}
