package be.steby.CoreProject.bll.domains.admin.exceptions.reactivation;


import be.steby.CoreProject.bll.domains.admin.exceptions.AdminDomainException;

/**
 * Exception thrown when justification is required but missing/insufficient.
 * SIMPLE - just message and status, like the project pattern.
 */
public class JustificationRequiredException extends AdminDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "JUSTIFICATION_REQUIRED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public JustificationRequiredException(String message) {
        super(message, 400); // Bad Request
    }

    public JustificationRequiredException(String message, int status) {
        super(message, status);
    }

}