package be.steby.CoreProject.bll.domains.admin.exceptions.reactivation;

import be.steby.CoreProject.bll.domains.admin.exceptions.AdminDomainException;

/**
 * Exception thrown when attempting to reactivate a category that can never be reactivated.
 */
public class NeverReactivatableException extends AdminDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "NEVER_REACTIVATABLE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public NeverReactivatableException(String message) {
        super(message, 422); // Unprocessable Entity
    }

    public NeverReactivatableException(String message, int status) {
        super(message, status);
    }
}