package be.steby.CoreProject.bll.domains.crm.lead.exceptions;

/**
 * Exception thrown when honeypot field is filled (bot detected).
 *
 * <p>This exception should be handled silently - return a fake success
 * response to avoid informing bots that they were detected.</p>
 */
public class HoneypotDetectedException extends LeadDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "HONEYPOT_DETECTED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public HoneypotDetectedException(String message) {
        super(message);
    }
}