package be.steby.CoreProject.bll.domains.crm.lead.exceptions;

/**
 * Exception thrown when inquiry validation fails.
 */
public class LeadValidationException extends LeadDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "LEAD_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public LeadValidationException(String message) {
        super(message);
    }
}