package be.steby.CoreProject.bll.domains.crm.lead.exceptions;

/**
 * Exception thrown when inquiry rate limit is exceeded.
 */
public class LeadRateLimitException extends LeadDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "LEAD_RATE_LIMIT";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public LeadRateLimitException(String message) {
        super(message);
    }
}