package be.steby.CoreProject.bll.domains.lead.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for inquiry domain errors.
 */
public class LeadDomainException extends CoreProjectException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "LEAD_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public LeadDomainException(String message) {
        super(message);
    }

    public LeadDomainException(String message, Throwable cause) {
        super(message, cause);
    }
}