package be.steby.CoreProject.bll.domains.emailaddress.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

public class EmailSendingException extends CoreProjectException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "EMAIL_SENDING";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public EmailSendingException(String message) {
        super(message, 500);
    }

    public EmailSendingException(String message, int status) {
        super(message, status);
    }
}
