package be.steby.CoreProject.bll.domains.emailaddress.exceptions;

/**
 * Exception lancée lors de problèmes de validation structurelle des adresses email,
 * comme un email manquant, vide ou mal formaté.
 */
public class EmailValidationException extends EmailDomainException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "EMAIL_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Crée une nouvelle exception avec un message spécifique.
     *
     * @param message Message décrivant le problème de validation
     */
    public EmailValidationException(String message) {
        super(message);
    }

    /**
     * Crée une nouvelle exception avec un message et un code de statut spécifique.
     *
     * @param message Message décrivant le problème de validation
     * @param status Code de statut HTTP
     */
    public EmailValidationException(String message, int status) {
        super(message, status);
    }
}