package be.steby.CoreProject.bll.domains.password.exceptions;

/**
 * Exception lancée lorsqu'un mot de passe ne respecte pas les critères de sécurité
 * ou les règles métier définies.
 */
public class InvalidPasswordException extends PasswordDomainException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_PASSWORD";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Crée une nouvelle exception avec un message spécifique.
     *
     * @param message Message décrivant pourquoi le mot de passe est invalide
     */
    public InvalidPasswordException(String message) {
        super(message);
    }

    /**
     * Crée une nouvelle exception avec un message et un statut spécifique.
     *
     * @param message Message décrivant pourquoi le mot de passe est invalide
     * @param status Code de statut HTTP
     */
    public InvalidPasswordException(String message, int status) {
        super(message, status);
    }
}