package be.steby.CoreProject.bll.domains.password.exceptions;

public class NoPasswordDefinedException extends PasswordDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "NO_PASSWORD_DEFINED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public NoPasswordDefinedException(String message) {
        super(message);
    }
}
