package be.steby.CoreProject.bll.domains.password.exceptions;

/**
 * Exception lancée lorsque le mot de passe actuel fourni ne correspond pas
 * au mot de passe enregistré de l'utilisateur.
 */
public class PasswordMismatchException extends PasswordDomainException {

  
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PASSWORD_MISMATCH";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
   * Crée une nouvelle exception avec un message par défaut.
   */
  public PasswordMismatchException() {
    super("Le mot de passe actuel est incorrect");
  }

  /**
   * Crée une nouvelle exception avec un message personnalisé.
   *
   * @param message Message personnalisé
   */
  public PasswordMismatchException(String message) {
    super(message);
  }
}