package be.steby.CoreProject.bll.domains.password.exceptions;

/**
 * Exception lancée lors de problèmes de validation structurelle des mots de passe,
 * comme un mot de passe manquant ou vide.
 */
public class PasswordValidationException extends PasswordDomainException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PASSWORD_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Crée une nouvelle exception avec un message spécifique.
     *
     * @param message Message décrivant le problème de validation
     */
    public PasswordValidationException(String message) {
        super(message);
    }
}