package be.steby.CoreProject.bll.domains.password.exceptions;

/**
 * Exception thrown when a user attempts to define a password
 * but already has one defined.
 */
public class PasswordAlreadyDefinedException extends PasswordDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PASSWORD_ALREADY_DEFINED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public PasswordAlreadyDefinedException(String message) {
        super(message, 400);
    }
}