package be.steby.CoreProject.bll.domains.crm.contact.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all contact domain-related exceptions.
 *
 * <p>This abstract class extends {@link CoreProjectException} to integrate
 * with the global exception handling system via {@code ControllerAdvisor}.</p>
 *
 * <p>All specific contact exceptions should extend this class to ensure
 * consistent error handling across the contact domain.</p>
 *
 * <h3>Exception hierarchy</h3>
 * <pre>
 * CoreProjectException
 * └── ContactDomainException
 *     ├── ContactNotFoundException
 *     ├── ContactEmailAlreadyExistsException
 *     ├── ContactValidationException
 *     ├── ContactStatusTransitionException
 *     └── ContactAlreadyLinkedToUserException
 * </pre>
 *
 * @see CoreProjectException
 * @see ContactNotFoundException
 * @see ContactEmailAlreadyExistsException
 * @see ContactValidationException
 * @see ContactStatusTransitionException
 * @see ContactAlreadyLinkedToUserException
 */
public abstract class ContactDomainException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new contact domain exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public ContactDomainException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new contact domain exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactDomainException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new contact domain exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new contact domain exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}