package be.steby.CoreProject.bll.domains.crm.contact.exceptions;

/**
 * Exception thrown when a contact cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} or {@code email}
 * returns no result in the repository.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see ContactDomainException
 */
public class ContactNotFoundException extends ContactDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public ContactNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a contact not found by its internal id.
     *
     * @param id the internal id that yielded no result
     * @return a new ContactNotFoundException
     */
    public static ContactNotFoundException byId(Long id) {
        return new ContactNotFoundException("Contact not found with id: " + id);
    }

    /**
     * Creates an exception for a contact not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new ContactNotFoundException
     */
    public static ContactNotFoundException byPublicId(String publicId) {
        return new ContactNotFoundException("Contact not found with publicId: " + publicId);
    }

    /**
     * Creates an exception for a contact not found by email address.
     *
     * @param email the email address that yielded no result
     * @return a new ContactNotFoundException
     */
    public static ContactNotFoundException byEmail(String email) {
        return new ContactNotFoundException("Contact not found with email: " + email);
    }

    /**
     * Creates an exception for a contact not found by origin lead public UUID.
     *
     * @param leadPublicId the lead public UUID that yielded no result
     * @return a new ContactNotFoundException
     */
    public static ContactNotFoundException byOriginLeadPublicId(String leadPublicId) {
        return new ContactNotFoundException("Contact not found for lead: " + leadPublicId);
    }
}