package be.steby.CoreProject.pl.domains.auth.models.requests;

import jakarta.validation.constraints.Pattern;

/**
 * Request payload for testing TOTP two-factor authentication codes.
 *
 * <p>This record encapsulates the verification code entered by a user when testing
 * their TOTP (Time-based One-Time Password) configuration. The code is generated
 * by authenticator apps like Google Authenticator, Microsoft Authenticator,
 * Authy, or any RFC 6238 compliant application.
 *
 * <p><strong>Usage Context:</strong>
 * <ul>
 *   <li>Used during TOTP 2FA setup to verify proper configuration</li>
 *   <li>Allows users to test their authenticator app before completing setup</li>
 *   <li>Validates that the time synchronization between user device and server is correct</li>
 * </ul>
 */
public record TotpTestRequest(
        /**
         * The 6-digit TOTP verification code from the user's authenticator app.
         *
         * <p>This code is generated by TOTP-compatible authenticator applications
         * using the shared secret key configured during the TOTP setup process.
         * The code changes every 30 seconds and must be used within its validity window.
         *
         * <p><strong>Expected Format:</strong> 6 consecutive digits (0-9)
         * <br><strong>Examples:</strong> "123456", "000789", "999999"
         *
         * @apiNote Leading zeros are preserved and significant for TOTP validation
         *
         * @validation
         * <ul>
         *   <li>@NotBlank - Cannot be null, empty, or contain only whitespace</li>
         *   <li>@Size(min=6, max=6) - Must be exactly 6 characters long</li>
         *   <li>@Pattern - Must contain only numeric digits (0-9)</li>
         * </ul>
         */
        @Pattern(regexp = "^[0-9]{6}$", message = "Verification code must be 6 digits")
        String code
    ) {}