package be.steby.CoreProject.bll.domains.crm.organisation.exceptions;

/**
 * Exception thrown when an organisation cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} or {@code name}
 * returns no result in the repository.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see OrganisationDomainException
 */
public class OrganisationNotFoundException extends OrganisationDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ORGANISATION_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public OrganisationNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public OrganisationNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public OrganisationNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public OrganisationNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for an organisation not found by its internal id.
     *
     * @param id the internal id that yielded no result
     * @return a new OrganisationNotFoundException
     */
    public static OrganisationNotFoundException byId(Long id) {
        return new OrganisationNotFoundException("Organisation not found with id: " + id);
    }

    /**
     * Creates an exception for an organisation not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new OrganisationNotFoundException
     */
    public static OrganisationNotFoundException byPublicId(String publicId) {
        return new OrganisationNotFoundException("Organisation not found with publicId: " + publicId);
    }

    /**
     * Creates an exception for an organisation not found by its name.
     *
     * @param name the name that yielded no result
     * @return a new OrganisationNotFoundException
     */
    public static OrganisationNotFoundException byName(String name) {
        return new OrganisationNotFoundException("Organisation not found with name: " + name);
    }
}
