package be.steby.CoreProject.bll.domains.storage.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all storage domain-related exceptions.
 *
 * <p>This abstract class extends {@link CoreProjectException} to integrate
 * with the global exception handling system via {@code ControllerAdvisor}.</p>
 *
 * <p>All specific storage exceptions should extend this class to ensure
 * consistent error handling across the storage domain.</p>
 *
 * @see CoreProjectException
 * @see FileStorageException
 * @see FileNotFoundException
 * @see FileValidationException
 * @see StorageQuotaExceededException
 */
public abstract class StorageDomainException extends CoreProjectException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "STORAGE_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Creates a new storage domain exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public StorageDomainException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new storage domain exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public StorageDomainException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new storage domain exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public StorageDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new storage domain exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public StorageDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}