package be.steby.CoreProject.bll.domains.pipeline.exceptions;

/**
 * Exception thrown when a pipeline cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} or {@code name}
 * returns no result in the repository.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see PipelineDomainException
 */
public class PipelineNotFoundException extends PipelineDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public PipelineNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a pipeline not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new PipelineNotFoundException
     */
    public static PipelineNotFoundException byPublicId(String publicId) {
        return new PipelineNotFoundException("Pipeline not found with publicId: " + publicId);
    }

    /**
     * Creates an exception for a pipeline not found by its name.
     *
     * @param name the name that yielded no result
     * @return a new PipelineNotFoundException
     */
    public static PipelineNotFoundException byName(String name) {
        return new PipelineNotFoundException("Pipeline not found with name: " + name);
    }

    /**
     * Creates an exception when no default pipeline is configured.
     *
     * @return a new PipelineNotFoundException
     */
    public static PipelineNotFoundException noDefault() {
        return new PipelineNotFoundException("No default pipeline is configured");
    }
}