package be.steby.CoreProject.bll.domains.pipeline.exceptions;

/**
 * Exception thrown when a pipeline creation or update is attempted
 * with a name that is already registered to another pipeline.
 *
 * <p>Pipeline names must be unique (case-insensitive) to avoid confusion
 * in the deal creation form and dashboard headers.</p>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see PipelineDomainException
 */
public class PipelineNameAlreadyExistsException extends PipelineDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_NAME_ALREADY_EXISTS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public PipelineNameAlreadyExistsException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineNameAlreadyExistsException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineNameAlreadyExistsException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineNameAlreadyExistsException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a duplicate name detected during pipeline creation.
     *
     * @param name the name already registered to another pipeline
     * @return a new PipelineNameAlreadyExistsException
     */
    public static PipelineNameAlreadyExistsException forName(String name) {
        return new PipelineNameAlreadyExistsException(
                "A pipeline with name '" + name + "' already exists");
    }
}