package be.steby.CoreProject.bll.domains.pipeline.exceptions;

/**
 * Exception thrown when a pipeline step cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} returns no result,
 * or when a terminal step (Won / Lost) is expected but not configured
 * on the pipeline.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see PipelineDomainException
 */
public class PipelineStepNotFoundException extends PipelineDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_STEP_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public PipelineStepNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineStepNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineStepNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineStepNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a step not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new PipelineStepNotFoundException
     */
    public static PipelineStepNotFoundException byPublicId(String publicId) {
        return new PipelineStepNotFoundException("Pipeline step not found with publicId: " + publicId);
    }

    /**
     * Creates an exception for a step not found within a specific pipeline.
     *
     * @param stepPublicId     the public UUID of the step
     * @param pipelinePublicId the public UUID of the pipeline it was expected to belong to
     * @return a new PipelineStepNotFoundException
     */
    public static PipelineStepNotFoundException notInPipeline(String stepPublicId, String pipelinePublicId) {
        return new PipelineStepNotFoundException(
                "Pipeline step '" + stepPublicId + "' does not belong to pipeline '" + pipelinePublicId + "'");
    }

    /**
     * Creates an exception when no Won terminal step is configured on a pipeline.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineStepNotFoundException
     */
    public static PipelineStepNotFoundException noWonStep(String pipelinePublicId) {
        return new PipelineStepNotFoundException(
                "No Won terminal step configured on pipeline: " + pipelinePublicId);
    }

    /**
     * Creates an exception when no Lost terminal step is configured on a pipeline.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineStepNotFoundException
     */
    public static PipelineStepNotFoundException noLostStep(String pipelinePublicId) {
        return new PipelineStepNotFoundException(
                "No Lost terminal step configured on pipeline: " + pipelinePublicId);
    }
}