package be.steby.CoreProject.bll.domains.pipeline.exceptions;

/**
 * Exception thrown when a pipeline or pipeline step fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>A step has both {@code isWon} and {@code isLost} set to {@code true}</li>
 *   <li>A pipeline already has a Won terminal step and a second one is added</li>
 *   <li>A pipeline already has a Lost terminal step and a second one is added</li>
 *   <li>A reorder request is missing steps or contains unknown step public IDs</li>
 *   <li>A reorder request contains duplicate positions</li>
 *   <li>A pipeline name is blank or exceeds the allowed length</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see PipelineDomainException
 */
public class PipelineValidationException extends PipelineDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public PipelineValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when a step has both {@code isWon} and {@code isLost} set to {@code true}.
     *
     * @param stepName the name of the offending step
     * @return a new PipelineValidationException
     */
    public static PipelineValidationException mutuallyExclusiveTerminalFlags(String stepName) {
        return new PipelineValidationException(
                "Step '" + stepName + "' cannot have both isWon and isLost set to true");
    }

    /**
     * Creates an exception when a pipeline already has a Won terminal step.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineValidationException
     */
    public static PipelineValidationException duplicateWonStep(String pipelinePublicId) {
        return new PipelineValidationException(
                "Pipeline '" + pipelinePublicId + "' already has a Won terminal step");
    }

    /**
     * Creates an exception when a pipeline already has a Lost terminal step.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineValidationException
     */
    public static PipelineValidationException duplicateLostStep(String pipelinePublicId) {
        return new PipelineValidationException(
                "Pipeline '" + pipelinePublicId + "' already has a Lost terminal step");
    }

    /**
     * Creates an exception when a reorder request is missing one or more steps of the pipeline.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineValidationException
     */
    public static PipelineValidationException reorderIncomplete(String pipelinePublicId) {
        return new PipelineValidationException(
                "Reorder request for pipeline '" + pipelinePublicId + "' is missing one or more steps");
    }

    /**
     * Creates an exception when a reorder request contains duplicate positions.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new PipelineValidationException
     */
    public static PipelineValidationException reorderDuplicatePositions(String pipelinePublicId) {
        return new PipelineValidationException(
                "Reorder request for pipeline '" + pipelinePublicId + "' contains duplicate positions");
    }
}