package be.steby.CoreProject.bll.domains.pipeline.exceptions;

/**
 * Exception thrown when a destructive operation is attempted on a pipeline
 * that still has active (open) deals.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Deleting a pipeline that contains open deals</li>
 *   <li>Deleting a pipeline step that has deals currently sitting on it</li>
 * </ul>
 *
 * <p>The caller must either close or migrate all active deals to another
 * pipeline / step before retrying the operation.</p>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see PipelineDomainException
 */
public class PipelineHasActiveDealsException extends PipelineDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PIPELINE_HAS_ACTIVE_DEALS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public PipelineHasActiveDealsException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public PipelineHasActiveDealsException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public PipelineHasActiveDealsException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public PipelineHasActiveDealsException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when attempting to delete a pipeline that has open deals.
     *
     * @param pipelinePublicId the public UUID of the pipeline
     * @param activeDealsCount the number of open deals blocking the deletion
     * @return a new PipelineHasActiveDealsException
     */
    public static PipelineHasActiveDealsException onPipelineDelete(String pipelinePublicId, long activeDealsCount) {
        return new PipelineHasActiveDealsException(
                "Cannot delete pipeline '" + pipelinePublicId + "': " + activeDealsCount + " active deal(s) must be closed or migrated first");
    }

    /**
     * Creates an exception when attempting to delete a step that has deals sitting on it.
     *
     * @param stepPublicId     the public UUID of the step
     * @param activeDealsCount the number of deals currently at this step
     * @return a new PipelineHasActiveDealsException
     */
    public static PipelineHasActiveDealsException onStepDelete(String stepPublicId, long activeDealsCount) {
        return new PipelineHasActiveDealsException(
                "Cannot delete step '" + stepPublicId + "': " + activeDealsCount + " active deal(s) must be moved first");
    }
}