package be.steby.CoreProject.bll.domains.admin.exceptions;

/**
 * Exception for admin domain permission violations.
 * Specific to administrative operations and role hierarchy.
 */
public class AdminPermissionException extends AdminDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ADMIN_PERMISSION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AdminPermissionException(String message) {
        super(message);
    }

    public AdminPermissionException(String message, int status) {
        super(message, status);
    }

    public AdminPermissionException(String message, Throwable cause) {
        super(message, cause);
    }
}