package be.steby.CoreProject.bll.domains.crm.deal.exceptions;

/**
 * Exception thrown when attempting to move a deal to a stage that does not
 * belong to the deal's current pipeline.
 *
 * <p>This exception is raised during {@code moveToStage} when the target
 * {@link be.steby.CoreProject.dl.entities.crm.PipelineStep} belongs to a different
 * {@link be.steby.CoreProject.dl.entities.crm.Pipeline} than the one the deal is in.</p>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see DealDomainException
 */
public class DealStageNotInPipelineException extends DealDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEAL_STAGE_NOT_IN_PIPELINE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public DealStageNotInPipelineException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public DealStageNotInPipelineException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public DealStageNotInPipelineException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public DealStageNotInPipelineException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception indicating a stage does not belong to the deal's pipeline.
     *
     * @param stagePublicId    the public UUID of the requested stage
     * @param pipelinePublicId the public UUID of the deal's current pipeline
     * @return a new DealStageNotInPipelineException
     */
    public static DealStageNotInPipelineException forStageAndPipeline(String stagePublicId,
                                                                        String pipelinePublicId) {
        return new DealStageNotInPipelineException(
                "Stage '" + stagePublicId + "' does not belong to pipeline '" + pipelinePublicId + "'");
    }
}
