package be.steby.CoreProject.bll.domains.crm.deal.exceptions;

/**
 * Exception thrown when deal data fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Required field missing (title, pipeline, stage, contact, assigned commercial)</li>
 *   <li>Stage does not belong to the specified pipeline</li>
 *   <li>Field value exceeding maximum allowed length</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see DealDomainException
 */
public class DealValidationException extends DealDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEAL_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public DealValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public DealValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public DealValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public DealValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a missing required field.
     *
     * @param field the name of the missing field
     * @return a new DealValidationException
     */
    public static DealValidationException missingRequiredField(String field) {
        return new DealValidationException(
                "Required field is missing: " + field);
    }

    /**
     * Creates an exception when a stage does not belong to the specified pipeline.
     *
     * @param stagePublicId    the public UUID of the stage
     * @param pipelinePublicId the public UUID of the pipeline
     * @return a new DealValidationException
     */
    public static DealValidationException invalidStageForPipeline(String stagePublicId,
                                                                    String pipelinePublicId) {
        return new DealValidationException(
                "Stage '" + stagePublicId + "' does not belong to pipeline '" + pipelinePublicId + "'");
    }
}
