package be.steby.CoreProject.bll.domains.crm.deal.exceptions;

/**
 * Exception thrown when an operation is attempted on a deal that has already
 * been closed (status {@code WON} or {@code LOST}).
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Attempting to update fields on a closed deal</li>
 *   <li>Attempting to move a closed deal to a new stage</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see DealDomainException
 */
public class DealAlreadyClosedException extends DealDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEAL_ALREADY_CLOSED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public DealAlreadyClosedException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public DealAlreadyClosedException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public DealAlreadyClosedException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public DealAlreadyClosedException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception indicating a deal is already closed.
     *
     * @param publicId the public UUID of the closed deal
     * @return a new DealAlreadyClosedException
     */
    public static DealAlreadyClosedException forDeal(String publicId) {
        return new DealAlreadyClosedException("Deal is already closed: " + publicId);
    }
}
