package be.steby.CoreProject.dl.enums;

public enum AttemptType {
    ACCOUNT_CONFIRMATION,
    ACCOUNT_DEACTIVATION,
    ACCOUNT_REACTIVATION,
    DEVICE_CONFIRMATION,
    EMAIL_CONFIRMATION,
    PASSWORD_RESSET,

}
