package be.steby.CoreProject.bll.common.exceptions.phone;


/**
 * Exception thrown when phone verification token is invalid or expired.
 * Used when JWT phone verification token validation fails.
 * 
 * @author Steby Team
 * @since 2.0.0
 */
public class InvalidPhoneVerificationTokenException extends PhoneException {
    

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_PHONE_VERIFICATION_TOKEN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidPhoneVerificationTokenException(String message) {
        super(message);
    }

    public InvalidPhoneVerificationTokenException(String message, int status) {
        super(message, status);
    }
    
    public InvalidPhoneVerificationTokenException(String message, Throwable cause) {
        super(message, cause);
    }
}