package be.steby.CoreProject.bll.common.exceptions.phone;


import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all phone operations.
 * Extends CoreProjectException to follow the project's exception hierarchy.
 */
public class PhoneException extends CoreProjectException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "PHONE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public PhoneException(String message) {
        super(message);
    }

    public PhoneException(String message, int status) {
        super(message, status);
    }

    public PhoneException(String message, Throwable cause) {
        super(message, cause);
    }
}