package be.steby.CoreProject.bll.common.exceptions.phone;

/**
 * Exception thrown when SMS sending operation fails.
 * Similar to EmailSendingException but for SMS operations.
 */
public class SmsSendingException extends PhoneException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "SMS_SENDING";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public SmsSendingException(String message) {
        super(message);
    }

    public SmsSendingException(String message, Throwable cause) {
        super(message, cause);
    }
}