package be.steby.CoreProject.bll.domains.commercialaction.exceptions;

/**
 * Exception thrown when a commercial action cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} returns no result
 * in the repository.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see CommercialActionDomainException
 */
public class CommercialActionNotFoundException extends CommercialActionDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "COMMERCIAL_ACTION_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public CommercialActionNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public CommercialActionNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public CommercialActionNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public CommercialActionNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a commercial action not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new CommercialActionNotFoundException
     */
    public static CommercialActionNotFoundException byPublicId(String publicId) {
        return new CommercialActionNotFoundException(
                "CommercialAction not found with publicId: " + publicId);
    }
}
