package be.steby.CoreProject.bll.domains.commercialaction.exceptions;

/**
 * Exception thrown when commercial action data fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Neither {@code dealPublicId} nor {@code contactPublicId} is provided on creation</li>
 *   <li>{@code assignedToPublicId} is missing from the create request</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see CommercialActionDomainException
 */
public class CommercialActionValidationException extends CommercialActionDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "COMMERCIAL_ACTION_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public CommercialActionValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public CommercialActionValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public CommercialActionValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public CommercialActionValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when neither {@code dealPublicId} nor {@code contactPublicId}
     * is provided on the create request.
     *
     * @return a new CommercialActionValidationException
     */
    public static CommercialActionValidationException neitherDealNorContact() {
        return new CommercialActionValidationException(
                "At least one of dealPublicId or contactPublicId must be provided");
    }

    /**
     * Creates an exception when {@code assignedToPublicId} is missing from the request.
     *
     * @return a new CommercialActionValidationException
     */
    public static CommercialActionValidationException missingAssignee() {
        return new CommercialActionValidationException(
                "assignedToPublicId is required");
    }
}
