package be.steby.CoreProject.bll.domains.organisation.exceptions;

/**
 * Exception thrown when an organisation creation or update is attempted
 * with a name that already exists in the CRM (case-insensitive).
 *
 * <p>Organisation names are enforced as unique to prevent CRM data duplication.
 * The repository provides {@code existsByNameIgnoreCase} for this check.</p>
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Manual creation — an organisation with the same name already exists</li>
 *   <li>Update — the new name conflicts with another existing organisation</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see OrganisationDomainException
 */
public class OrganisationNameAlreadyExistsException extends OrganisationDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ORGANISATION_NAME_ALREADY_EXISTS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public OrganisationNameAlreadyExistsException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public OrganisationNameAlreadyExistsException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public OrganisationNameAlreadyExistsException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public OrganisationNameAlreadyExistsException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a duplicate name detected during organisation creation.
     *
     * @param name the name already registered to another organisation
     * @return a new OrganisationNameAlreadyExistsException
     */
    public static OrganisationNameAlreadyExistsException forName(String name) {
        return new OrganisationNameAlreadyExistsException(
                "An organisation with name '" + name + "' already exists");
    }

    /**
     * Creates an exception for a duplicate name detected during an update.
     *
     * @param name             the new name that conflicts with an existing organisation
     * @param conflictPublicId public UUID of the organisation already using that name
     * @return a new OrganisationNameAlreadyExistsException
     */
    public static OrganisationNameAlreadyExistsException onUpdate(String name, String conflictPublicId) {
        return new OrganisationNameAlreadyExistsException(
                "Cannot rename organisation: name '" + name + "' is already used by organisation '" + conflictPublicId + "'");
    }
}
