package be.steby.CoreProject.bll.domains.organisation.exceptions;

/**
 * Exception thrown when organisation data fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Required field missing (name)</li>
 *   <li>Field value exceeding maximum allowed length</li>
 *   <li>Invalid website URL format</li>
 *   <li>Invalid phone number format</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see OrganisationDomainException
 */
public class OrganisationValidationException extends OrganisationDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ORGANISATION_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public OrganisationValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public OrganisationValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public OrganisationValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public OrganisationValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a missing required field.
     *
     * @param fieldName the name of the missing field
     * @return a new OrganisationValidationException
     */
    public static OrganisationValidationException missingRequiredField(String fieldName) {
        return new OrganisationValidationException(
                "Required field is missing: " + fieldName);
    }

    /**
     * Creates an exception for a field exceeding its maximum allowed length.
     *
     * @param fieldName the name of the field
     * @param maxLength the maximum allowed length
     * @param actual    the actual length provided
     * @return a new OrganisationValidationException
     */
    public static OrganisationValidationException fieldTooLong(String fieldName, int maxLength, int actual) {
        return new OrganisationValidationException(
                "Field '" + fieldName + "' exceeds maximum length of " + maxLength +
                " characters (actual: " + actual + ")");
    }

    /**
     * Creates an exception for an invalid website URL format.
     *
     * @param website the invalid URL
     * @return a new OrganisationValidationException
     */
    public static OrganisationValidationException invalidWebsiteFormat(String website) {
        return new OrganisationValidationException(
                "Invalid website URL format: '" + website + "'");
    }

    /**
     * Creates an exception for an invalid phone number format.
     *
     * @param phone the invalid phone number
     * @return a new OrganisationValidationException
     */
    public static OrganisationValidationException invalidPhoneFormat(String phone) {
        return new OrganisationValidationException(
                "Invalid phone number format: '" + phone + "'");
    }
}
