package be.steby.CoreProject.bll.domains.organisation.exceptions;

/**
 * Exception thrown when an organisation merge operation cannot be completed.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Source and target are the same organisation</li>
 *   <li>Source or target organisation is not found</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see OrganisationDomainException
 * @see be.steby.CoreProject.bll.domains.organisation.models.OrganisationMergeRequest
 */
public class OrganisationMergeException extends OrganisationDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ORGANISATION_MERGE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public OrganisationMergeException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public OrganisationMergeException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public OrganisationMergeException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public OrganisationMergeException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when source and target are the same organisation.
     *
     * @param publicId the public UUID used for both source and target
     * @return a new OrganisationMergeException
     */
    public static OrganisationMergeException sameOrganisation(String publicId) {
        return new OrganisationMergeException(
                "Cannot merge organisation with itself: '" + publicId + "'");
    }
}
