package be.steby.CoreProject.bll.domains.organisation.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all organisation domain-related exceptions.
 *
 * <p>This abstract class extends {@link CoreProjectException} to integrate
 * with the global exception handling system via {@code ControllerAdvisor}.</p>
 *
 * <p>All specific organisation exceptions should extend this class to ensure
 * consistent error handling across the organisation domain.</p>
 *
 * <h3>Exception hierarchy</h3>
 * <pre>
 * CoreProjectException
 * └── OrganisationDomainException
 *     ├── OrganisationNotFoundException
 *     ├── OrganisationNameAlreadyExistsException
 *     ├── OrganisationValidationException
 *     └── OrganisationMergeException
 * </pre>
 *
 * @see CoreProjectException
 * @see OrganisationNotFoundException
 * @see OrganisationNameAlreadyExistsException
 * @see OrganisationValidationException
 * @see OrganisationMergeException
 */
public abstract class OrganisationDomainException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ORGANISATION_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new organisation domain exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public OrganisationDomainException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new organisation domain exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public OrganisationDomainException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new organisation domain exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public OrganisationDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new organisation domain exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public OrganisationDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}
