package be.steby.CoreProject.bll.domains.auth.exceptions.twofactor;

import be.steby.CoreProject.bll.domains.auth.exceptions.AuthDomainException;

/**
 * Exception thrown when attempting to enable email-based 2FA for a user
 * who already has email 2FA enabled.
 * 
 * This prevents duplicate email 2FA configurations and ensures data consistency.
 * The client should check the current 2FA status before attempting to enable
 * additional methods.
 * 
 * HTTP Status: 409 Conflict - The request conflicts with the current state
 * of the resource (user already has email 2FA enabled).
 * 
 * @author Steby Team
 * @since 2.0.0
 */
public class EmailTwoFactorAlreadyEnabledException extends TwoFactorDomainException {
    
    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "EMAIL_TWO_FACTOR_ALREADY_ENABLED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Creates a new exception with a descriptive message.
     * Uses HTTP 409 Conflict status to indicate the resource conflict.
     * 
     * @param message detailed error message explaining the conflict
     */
    public EmailTwoFactorAlreadyEnabledException(String message) {
        super(message, 409);
    }
    
    /**
     * Creates a new exception with a default message.
     * Provides a standard user-friendly error message.
     */
    public EmailTwoFactorAlreadyEnabledException() {
        super("Email two-factor authentication is already enabled for this user", 409);
    }
    
    /**
     * Creates a new exception with a custom message and cause.
     * Useful when wrapping lower-level exceptions.
     * 
     * @param message detailed error message
     * @param cause the underlying cause of this exception
     */
    public EmailTwoFactorAlreadyEnabledException(String message, Throwable cause) {
        super(message, 409);
        initCause(cause);
    }
}