package be.steby.CoreProject.bll.domains.device.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all device domain exceptions.
 * Extends CoreProjectException to maintain consistency across the application.
 */
public class DeviceDomainException extends CoreProjectException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEVICE_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public DeviceDomainException(String message) {
        super(message);
    }

    public DeviceDomainException(String message, Throwable cause) {
        super(message, cause);
    }

    public DeviceDomainException(String message, int httpStatus) {
        super(message, httpStatus);
    }

    public DeviceDomainException(String message, int httpStatus, Throwable cause) {
        super(message, httpStatus, cause);
    }
}