package be.steby.CoreProject.bll.domains.device.exceptions;

import org.springframework.http.HttpStatus;

/**
 * Exception thrown when invalid arguments are provided to device operations.
 * Equivalent to IllegalArgumentException but specific to device domain.
 */
public class InvalidDeviceArgumentException extends DeviceDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_DEVICE_ARGUMENT";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidDeviceArgumentException(String message) {
        super(message, 400);
    }

    public InvalidDeviceArgumentException(String message, Throwable cause) {
        super(message, 400, cause);
    }
}