package be.steby.CoreProject.bll.domains.auth.exceptions;

/**
 * Exception thrown when a user account has been disabled by an administrator.
 * This should result in a 403 Forbidden response.
 */
public class AccountDisabledException extends AuthDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ACCOUNT_DISABLED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AccountDisabledException(String message) {
        super(message, 403);
    }
}