package be.steby.CoreProject.bll.domains.auth.exceptions;

/**
 * Exception thrown when a user account or IP address is temporarily locked
 * due to excessive failed login attempts.
 * This is a temporary security measure to prevent brute force attacks.
 */
public class AccountTemporarilyLockedException extends AuthDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ACCOUNT_TEMPORARILY_LOCKED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AccountTemporarilyLockedException(String message) {
        super(message, 423);
    }

    public AccountTemporarilyLockedException(String message, int statusCode) {
        super(message, statusCode);
    }
}