package be.steby.CoreProject.bll.domains.auth.exceptions;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * Exception thrown when a user attempts to login with a blacklisted device.
 * This is a security-related exception that should result in a 403 Forbidden response.
 */
public class BlacklistedDeviceException extends DeviceSecurityException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "BLACKLISTED_DEVICE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public BlacklistedDeviceException(String message) {
        super(message, 403);
    }
}