package be.steby.CoreProject.bll.domains.auth.exceptions;

public class InvalidRefreshTokenException extends InvalidTokenException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_REFRESH_TOKEN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidRefreshTokenException(String message) {
        super(message, 401);
    }

    public InvalidRefreshTokenException() {
        super("Invalid or expired refresh token", 401);
    }
}