package be.steby.CoreProject.bll.domains.auth.exceptions;

/**
 * Generic exception for invalid token errors.
 * Base class for specific token validation exceptions.
 */
public class InvalidTokenException extends AuthDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_TOKEN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidTokenException(String message) {
        super(message, 400);
    }

    public InvalidTokenException() {
        super("Invalid or malformed token", 400);
    }
}