package be.steby.CoreProject.bll.domains.auth.exceptions;

public class InvalidOAuth2CredentialsException extends InvalidCredentialsException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_O_AUTH2_CREDENTIALS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidOAuth2CredentialsException(String message) {
        super(message);
    }
}
