package be.steby.CoreProject.bll.domains.auth.exceptions;

/**
 * Exception thrown when user provides invalid credentials (username/password).
 * This should result in a 401 Unauthorized response.
 */
public class InvalidCredentialsException extends AuthDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_CREDENTIALS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidCredentialsException(String message) {
        super(message, 401);
    }

}
