package be.steby.CoreProject.bll.domains.auth.exceptions;

public class OAuthOnlyAccountException extends AuthDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "O_AUTH_ONLY_ACCOUNT";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public OAuthOnlyAccountException(String message) {
        super(message, 400);  // ou 403 selon ta préférence
    }
}