package be.steby.CoreProject.bll.domains.gdpr.exceptions;

import be.steby.CoreProject.bll.domains.storage.exceptions.StorageDomainException;

/**
 * Thrown when a GDPR archive storage operation fails.
 */
public class GdprStorageException extends GdprDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "GDPR_STORAGE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public GdprStorageException(String message) {
        super(message);
    }

    public GdprStorageException(String message, Throwable cause) {
        super(message, cause);
    }
}