package be.steby.CoreProject.bll.domains.crm.contact.models;

import be.steby.CoreProject.dl.entities.crm.Lead;

/**
 * BLL request model for creating a {@link be.steby.CoreProject.dl.entities.crm.Contact}
 * from a converted {@link Lead}.
 *
 * <p>Built by the {@code LeadConvertedEventListener} from the published
 * {@code LeadConvertedEvent}, then passed to
 * {@code ContactService.createFromConvertedLead()}.</p>
 *
 * <h3>publicId</h3>
 * <p>The {@code contactPublicId} is pre-generated by {@code LeadServiceImpl.convert()}
 * before the event is published. This ensures the lead and the contact share
 * a correlation handle without requiring a direct cross-domain service call.</p>
 *
 * <h3>Name</h3>
 * <p>{@link Lead#getName()} is a single free-text field — the service layer
 * is responsible for splitting it into {@code firstName} / {@code lastName}
 * on a best-effort basis.</p>
 *
 * <h3>Organisation</h3>
 * <p>Optional — may be provided by the commercial during the conversion step
 * if the lead's company is already known in the CRM.</p>
 *
 * @param contactPublicId      pre-generated public UUID for the contact to be created
 * @param lead                 the originating lead entity (used for email, name, and traceability)
 * @param organisationPublicId public UUID of the organisation to link (optional)
 */
public record ContactCreateFromLeadRequest(
        String contactPublicId,
        Lead lead,
        String organisationPublicId
) {}