package be.steby.CoreProject.bll.domains.sport.exceptions;

import lombok.Getter;

/**
 * Exception thrown when attempting to import a GPX file that was already imported.
 *
 * @see SportDomainException
 */
@Getter
public class GpxAlreadyImportedException extends SportDomainException {

    private final String gpxFilePublicId;


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "GPX_ALREADY_IMPORTED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public GpxAlreadyImportedException(String gpxFilePublicId) {
        super("GPX file already imported: " + gpxFilePublicId, 409);
        this.gpxFilePublicId = gpxFilePublicId;
    }
}