package be.steby.CoreProject.bll.domains.sport.exceptions;

/**
 * Exception thrown when a sport track is not found.
 *
 * @see SportDomainException
 */
public class SportTrackNotFoundException extends SportDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "SPORT_TRACK_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public SportTrackNotFoundException(String publicId) {
        super("Sport track not found: " + publicId, 404);
    }

    public SportTrackNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }
}