package be.steby.CoreProject.bll.domains.deal.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all deal domain-related exceptions.
 *
 * <p>This abstract class extends {@link CoreProjectException} to integrate
 * with the global exception handling system via {@code ControllerAdvisor}.</p>
 *
 * <p>All specific deal exceptions should extend this class to ensure
 * consistent error handling across the deal domain.</p>
 *
 * <h3>Exception hierarchy</h3>
 * <pre>
 * CoreProjectException
 * └── DealDomainException
 *     ├── DealNotFoundException
 *     ├── DealAlreadyClosedException
 *     ├── DealValidationException
 *     └── DealStageNotInPipelineException
 * </pre>
 *
 * @see CoreProjectException
 * @see DealNotFoundException
 * @see DealAlreadyClosedException
 * @see DealValidationException
 * @see DealStageNotInPipelineException
 */
public abstract class DealDomainException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEAL_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new deal domain exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public DealDomainException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new deal domain exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public DealDomainException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new deal domain exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public DealDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new deal domain exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public DealDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}
