package be.steby.CoreProject.bll.domains.deal.exceptions;

/**
 * Exception thrown when a deal cannot be found.
 *
 * <p>Typically raised when a lookup by {@code publicId} or internal {@code id}
 * returns no result in the repository.</p>
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 *
 * @see DealDomainException
 */
public class DealNotFoundException extends DealDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DEAL_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     */
    public DealNotFoundException(String message) {
        super(message, 404);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public DealNotFoundException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 404 (Not Found).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public DealNotFoundException(String message, Throwable cause) {
        super(message, 404, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public DealNotFoundException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a deal not found by its internal id.
     *
     * @param id the internal id that yielded no result
     * @return a new DealNotFoundException
     */
    public static DealNotFoundException byId(Long id) {
        return new DealNotFoundException("Deal not found with id: " + id);
    }

    /**
     * Creates an exception for a deal not found by its public UUID.
     *
     * @param publicId the public UUID that yielded no result
     * @return a new DealNotFoundException
     */
    public static DealNotFoundException byPublicId(String publicId) {
        return new DealNotFoundException("Deal not found with publicId: " + publicId);
    }
}
