
security:
  jwt:
    secret: ${JWT_SECRET}

domains:
  auth:
    jwt:
      access-token-expiration: 3600000
      access-token-cookie-name: access_token
      refresh-token-cookie-name: refresh_token
    refresh-token-expiration: 604800000

  twofactor:
    jwt:
      expiration: 600000
      token-cookie-name: 2fa_token
      session-cookie-name: 2fa_session_token

  profile:
    jwt:
      phone-verification-expiration: 600000

  password:
    jwt:
      verification-expiration: 600000
      permission-expiration: 900000