security:
  password:
    min-length: 8
    max-length: 55
    require-uppercase: true
    require-lowercase: true
    require-digit: true
    require-special-char: true
    special-chars: "!@#$%^&*()_+-=[]{}\\;':\"\\|,.<>/?"