security:
  password:
    min-length: 8
    max-length: 55
    require-uppercase: true
    require-lowercase: true
    require-digit: true
    require-special-char: true
    special-chars: '!@#$%^&*-_=+'

  password-reset:
    token:
      expiration: 900000  # 15 minutes
      #expiration: 10000  # 1 second
    max-attempts: 3
    lockout-minutes: 30