package be.steby.CoreProject.bll.domains.interaction.exceptions;

/**
 * Exception thrown when interaction data fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Neither {@code dealPublicId} nor {@code contactPublicId} is provided</li>
 *   <li>A {@code CALL} interaction is submitted without {@code callLogDetails}</li>
 *   <li>An {@code EMAIL} interaction is submitted without {@code emailLogDetails}</li>
 *   <li>{@code callLogDetails} provided for a non-CALL interaction type</li>
 *   <li>{@code emailLogDetails} provided for a non-EMAIL interaction type</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see InteractionDomainException
 */
public class InteractionValidationException extends InteractionDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INTERACTION_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public InteractionValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public InteractionValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public InteractionValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public InteractionValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when neither {@code dealPublicId} nor {@code contactPublicId}
     * is provided on the create request.
     *
     * @return a new InteractionValidationException
     */
    public static InteractionValidationException neitherDealNorContact() {
        return new InteractionValidationException(
                "At least one of leadPublicId, dealPublicId, or contactPublicId must be provided");
    }

    /**
     * Creates an exception when a CALL interaction is submitted without {@code callLogDetails}.
     *
     * @return a new InteractionValidationException
     */
    public static InteractionValidationException callLogRequiredForCallType() {
        return new InteractionValidationException(
                "A callLog is required when type is CALL");
    }

    /**
     * Creates an exception when an EMAIL interaction is submitted without {@code emailLogDetails}.
     *
     * @return a new InteractionValidationException
     */
    public static InteractionValidationException emailLogRequiredForEmailType() {
        return new InteractionValidationException(
                "An emailLog is required when type is EMAIL");
    }

    /**
     * Creates an exception when {@code callLogDetails} is provided for a non-CALL interaction.
     *
     * @return a new InteractionValidationException
     */
    public static InteractionValidationException callLogOnlyForCallType() {
        return new InteractionValidationException(
                "callLog can only be provided when type is CALL");
    }

    /**
     * Creates an exception when {@code emailLogDetails} is provided for a non-EMAIL interaction.
     *
     * @return a new InteractionValidationException
     */
    public static InteractionValidationException emailLogOnlyForEmailType() {
        return new InteractionValidationException(
                "emailLog can only be provided when type is EMAIL");
    }
}
