package be.steby.CoreProject.bll.domains.user.exceptions;


/**
 * Exception thrown when invalid arguments are provided to user operations.
 * Equivalent to IllegalArgumentException but specific to user domain.
 */
public class InvalidUserArgumentException extends UserDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "INVALID_USER_ARGUMENT";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public InvalidUserArgumentException(String message) {
        super(message, 400);
    }

    public InvalidUserArgumentException(String message, Throwable cause) {
        super(message, cause);
    }
}