package be.steby.CoreProject.bll.domains.user.exceptions;

public class UserAlreadyActivatedException extends UserDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "USER_ALREADY_ACTIVATED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public UserAlreadyActivatedException(String message) {
        super(message, 409   );
    }
}