
    create table account_confirmation_token (
        id bigint not null,
        primary key (id)
    );

    create table account_deactivation_token (
        id bigint not null,
        reason_details varchar(500),
        deactivation_reason varchar(255) check (deactivation_reason in ('TAKING_A_BREAK','TOO_MUCH_TIME','PRIVACY_CONCERNS','ACCOUNT_CLEANUP','SWITCHING_ACCOUNTS','WORK_REQUIREMENTS','NOT_USEFUL','OTHER')),
        primary key (id)
    );

    create table account_deletion_token (
        id bigint not null,
        primary key (id)
    );

    create table account_reactivation_token (
        id bigint not null,
        primary key (id)
    );

    create table activity_log (
        successful boolean not null,
        created_at timestamp(6) with time zone not null,
        device_id bigint,
        id bigint generated by default as identity,
        target_device_id bigint,
        timestamp timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint,
        action_category varchar(20) not null,
        ip_address varchar(45),
        action_type varchar(50) not null,
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        action_details varchar(500),
        failure_reason varchar(255),
        location varchar(255),
        primary key (id)
    );

    create table address (
        country_code varchar(2) not null,
        latitude float(53),
        longitude float(53),
        validated boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        postal_code varchar(20),
        street_number varchar(20),
        created_by varchar(50),
        updated_by varchar(50),
        validation_source varchar(50),
        city varchar(100),
        state_province varchar(100),
        complement varchar(150),
        street_name varchar(150),
        public_id varchar(256) unique,
        formatted_address varchar(500),
        primary key (id)
    );

    create table address_link (
        active boolean not null,
        is_default boolean not null,
        verified_by_owner boolean not null,
        address_id bigint not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        valid_from timestamp(6) with time zone,
        valid_to timestamp(6) with time zone,
        verified_at timestamp(6) with time zone,
        address_type varchar(20) not null check (address_type in ('PRIMARY','BILLING','SHIPPING','RESIDENTIAL','PROFESSIONAL','TEMPORARY','LEGAL','WAREHOUSE','RETURN','OTHER')),
        modification_strategy varchar(20) check (modification_strategy in ('SHARED','COPY_ON_WRITE','OWNER_ONLY','IMMUTABLE','VERSIONED')),
        link_type varchar(30) not null,
        created_by varchar(50),
        label varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        notes varchar(500),
        primary key (id)
    );

    create table base_token (
        revoked boolean not null,
        created_at timestamp(6) with time zone not null,
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        token varchar(255) not null unique,
        token_type varchar(255) check (token_type in ('ACCOUNT_CONFIRMATION','ACCOUNT_DEACTIVATION','ACCOUNT_DELETION','ACCOUNT_REACTIVATION','DEVICE_CONFIRMATION','EMAIL_CONFIRMATION','PASSWORD_RESET','REFRESH_TOKEN','SMS_PASSWORD_RESET')),
        primary key (id)
    );

    create table calendar_event (
        all_day boolean not null,
        reminder_minutes integer,
        color_code varchar(7),
        address_id bigint,
        created_at timestamp(6) with time zone not null,
        end_date_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        start_date_time timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        recurrence varchar(20) not null check (recurrence in ('NONE','DAILY','WEEKLY','MONTHLY','YEARLY')),
        status varchar(20) not null check (status in ('TENTATIVE','CONFIRMED','CANCELLED')),
        source_public_id varchar(36),
        created_by varchar(50),
        source_type varchar(50),
        updated_by varchar(50),
        title varchar(200) not null,
        owner_public_id varchar(256) not null,
        public_id varchar(256) unique,
        location varchar(300),
        description TEXT,
        primary key (id)
    );

    create table commercial_action (
        duration_minutes integer,
        address_id bigint,
        assigned_to_id bigint not null,
        completed_at timestamp(6) with time zone,
        contact_id bigint,
        created_at timestamp(6) with time zone not null,
        deal_id bigint,
        due_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        lead_id bigint,
        reminder_at timestamp(6) with time zone,
        reminder_sent_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        priority varchar(10) not null check (priority in ('LOW','MEDIUM','HIGH')),
        status varchar(15) not null check (status in ('PENDING','DONE','CANCELLED')),
        type varchar(15) not null check (type in ('TASK','CALL','EMAIL','MEETING','DEMO')),
        created_by varchar(50),
        updated_by varchar(50),
        title varchar(200) not null,
        public_id varchar(256) unique,
        location varchar(300),
        description TEXT,
        primary key (id)
    );

    create table contact_tag (
        contact_id bigint not null,
        tag_id bigint not null,
        primary key (contact_id, tag_id)
    );

    create table crm_call_log (
        duration_seconds integer,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        interaction_id bigint not null unique,
        updated_at timestamp(6) with time zone not null,
        status varchar(15) not null check (status in ('ANSWERED','VOICEMAIL','NO_ANSWER')),
        phone_number varchar(30),
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        recording_url varchar(500),
        primary key (id)
    );

    create table crm_change_log (
        changed_at timestamp(6) with time zone not null,
        changed_by_id bigint,
        id bigint generated by default as identity,
        entity_type varchar(20) not null check (entity_type in ('CONTACT','DEAL','LEAD','ORGANISATION')),
        entity_public_id varchar(36),
        public_id varchar(36) not null unique,
        field_name varchar(50) not null,
        new_value varchar(1000),
        old_value varchar(1000),
        primary key (id)
    );

    create table crm_contact (
        assigned_to_id bigint,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        lead_id bigint unique,
        organisation_id bigint,
        updated_at timestamp(6) with time zone not null,
        user_id bigint unique,
        status varchar(20) not null check (status in ('NEW','ENGAGED','QUALIFIED','CLIENT','LOST','INACTIVE')),
        phone varchar(30),
        created_by varchar(50),
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        updated_by varchar(50),
        job_title varchar(100),
        email varchar(254) not null,
        public_id varchar(256) unique,
        notes TEXT,
        primary key (id)
    );

    create table crm_deal (
        amount numeric(15,2),
        currency varchar(3),
        expected_close_date date,
        assigned_to_id bigint not null,
        closed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        organisation_id bigint,
        pipeline_id bigint not null,
        stage_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        status varchar(10) not null check (status in ('OPEN','WON','LOST')),
        created_by varchar(50),
        updated_by varchar(50),
        title varchar(200) not null,
        public_id varchar(256) unique,
        lost_reason TEXT,
        notes TEXT,
        primary key (id)
    );

    create table crm_email_log (
        clicked_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        interaction_id bigint not null unique,
        opened_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        body_snippet varchar(300),
        external_message_id varchar(255),
        subject varchar(255) not null,
        primary key (id)
    );

    create table crm_interaction (
        duration_minutes integer,
        contact_id bigint,
        created_at timestamp(6) with time zone not null,
        deal_id bigint,
        id bigint generated by default as identity,
        lead_id bigint,
        occurred_at timestamp(6) with time zone not null,
        performed_by_id bigint,
        updated_at timestamp(6) with time zone not null,
        direction varchar(10) check (direction in ('OUTBOUND','INBOUND')),
        outcome varchar(10) check (outcome in ('POSITIVE','NEUTRAL','NEGATIVE','NO_ANSWER')),
        type varchar(20) not null check (type in ('CALL','EMAIL','MEETING','DEMO','NOTE','VISIT','ACTION_DONE','CONTACT_FORM')),
        created_by varchar(50),
        updated_by varchar(50),
        subject varchar(200) not null,
        public_id varchar(256) unique,
        notes TEXT,
        primary key (id)
    );

    create table crm_organisation (
        address_id bigint,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        size varchar(20) check (size in ('MICRO','SMALL','MEDIUM','LARGE','ENTERPRISE')),
        status varchar(20) not null check (status in ('PROSPECT','CLIENT')),
        phone varchar(30),
        created_by varchar(50),
        updated_by varchar(50),
        industry varchar(100),
        name varchar(150) not null,
        public_id varchar(256) unique,
        notes TEXT,
        website varchar(255),
        primary key (id)
    );

    create table crm_pipeline (
        display_order integer not null,
        is_default boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        updated_by varchar(50),
        name varchar(100) not null,
        public_id varchar(256) unique,
        description varchar(500),
        primary key (id)
    );

    create table crm_pipeline_step (
        is_lost boolean not null,
        is_won boolean not null,
        position integer not null,
        win_probability integer not null,
        color varchar(7),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        pipeline_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        updated_by varchar(50),
        name varchar(100) not null,
        public_id varchar(256) unique,
        primary key (id)
    );

    create table crm_support_ticket (
        assigned_to_id bigint,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        submitted_by_id bigint,
        updated_at timestamp(6) with time zone not null,
        status varchar(15) not null check (status in ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
        source varchar(20) not null check (source in ('INTERNAL','PUBLIC_FORM')),
        ip_address varchar(45),
        created_by varchar(50),
        updated_by varchar(50),
        reporter_name varchar(150),
        reporter_email varchar(254),
        public_id varchar(256) unique,
        description TEXT,
        subject varchar(255) not null,
        primary key (id)
    );

    create table crm_tag (
        color varchar(7) not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        name varchar(50) not null unique,
        updated_by varchar(50),
        public_id varchar(256) unique,
        primary key (id)
    );

    create table deal_contact_role (
        is_primary boolean not null,
        contact_id bigint not null,
        created_at timestamp(6) with time zone not null,
        deal_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        role varchar(20) not null check (role in ('DECISION_MAKER','INFLUENCER','SIGNER','TECHNICAL','USER','OTHER')),
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        primary key (id),
        constraint uq_dcr_deal_contact unique (deal_id, contact_id)
    );

    create table deal_stage_history (
        deal_id bigint not null,
        entered_at timestamp(6) with time zone not null,
        exited_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        pipeline_step_id bigint not null,
        primary key (id)
    );

    create table deal_tag (
        deal_id bigint not null,
        tag_id bigint not null,
        primary key (deal_id, tag_id)
    );

    create table device_confirmation_token (
        device_id bigint,
        id bigint not null,
        primary key (id)
    );

    create table devices (
        blacklisted boolean not null,
        confirmed boolean not null,
        first_device_used boolean,
        logged_out boolean not null,
        blacklisted_time timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        first_seen timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_seen timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        last_ip_address varchar(45),
        browser_version varchar(50),
        created_by varchar(50),
        device_cpu varchar(50),
        device_cpu_bits varchar(50),
        language varchar(50),
        os_version varchar(50),
        updated_by varchar(50),
        browser varchar(100),
        device_brand varchar(100),
        device_class varchar(100),
        operating_system varchar(100),
        public_id varchar(256) unique,
        device_trust_level varchar(255) not null check (device_trust_level in ('UNTRUSTED','BASIC','TRUSTED','HIGHLY_TRUSTED')),
        device_type varchar(255) not null,
        fingerprint varchar(255) not null unique,
        location varchar(255),
        primary key (id)
    );

    create table email_confirmation_token (
        confirmed boolean not null,
        id bigint not null,
        new_email_address varchar(255),
        primary key (id)
    );

    create table failed_email (
        max_retries integer not null,
        retry_count integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        next_retry_at timestamp(6) with time zone,
        original_failure_at timestamp(6) with time zone not null,
        sent_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        status varchar(20) not null check (status in ('PENDING','RETRYING','SENT','FAILED')),
        subject varchar(500) not null,
        last_failure_reason varchar(2000),
        recipients varchar(2000) not null,
        html_content TEXT not null,
        last_exception_trace TEXT,
        primary key (id)
    );

    create table failed_geocoding (
        retry_count integer not null,
        address_id bigint not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_retry_at timestamp(6),
        updated_at timestamp(6) with time zone not null,
        status varchar(20) not null check (status in ('PENDING','RETRYING','SUCCESS','FAILED')),
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        error_message TEXT,
        primary key (id)
    );

    create table failed_sms (
        max_retries integer not null,
        retry_count integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        next_retry_at timestamp(6) with time zone,
        original_failure_at timestamp(6) with time zone not null,
        sent_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        recipient varchar(20) not null,
        status varchar(20) not null check (status in ('PENDING','RETRYING','SENT','FAILED')),
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        content varchar(1600) not null,
        last_failure_reason varchar(2000),
        last_exception_trace TEXT,
        primary key (id)
    );

    create table gdpr_export_request (
        confirmed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        downloaded_at timestamp(6) with time zone,
        expires_at timestamp(6) with time zone,
        generated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        status varchar(20) not null check (status in ('PENDING','PROCESSING','READY','DOWNLOADED','EXPIRED','FAILED')),
        download_token varchar(36) not null unique,
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        failure_reason varchar(500),
        primary key (id)
    );

    create table lead (
        assigned_to_id bigint,
        converted_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        submitted_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        civility varchar(10) check (civility in ('MR','MRS')),
        lead_type varchar(20) not null check (lead_type in ('GENERAL','COMMERCIAL','PARTNERSHIP','PRESS','OTHER')),
        phone varchar(20),
        status varchar(20) not null check (status in ('NEW','IN_REVIEW','CONVERTED','REJECTED')),
        lead_source varchar(30) check (lead_source in ('CONTACT_FORM','PHONE','EMAIL','REFERRAL','SOCIAL_MEDIA','PAID_CAMPAIGN','ORGANIC_SEARCH','EVENT','MANUAL','FACEBOOK_ADS','LINKEDIN_ADS','TYPEFORM','OTHER')),
        ip_address varchar(45),
        created_by varchar(50),
        updated_by varchar(50),
        first_name varchar(100),
        last_name varchar(100),
        job_title varchar(150),
        organisation_name varchar(200),
        public_id varchar(256) unique,
        email varchar(255) not null,
        message TEXT,
        rejection_reason varchar(255),
        subject varchar(255) not null,
        primary key (id)
    );

    create table lead_tag (
        lead_id bigint not null,
        tag_id bigint not null,
        primary key (lead_id, tag_id)
    );

    create table login_attempt (
        attempt_count integer not null,
        is_blocked boolean not null,
        blocked_until timestamp(6) with time zone,
        first_attempt_time timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_attempt_time timestamp(6) with time zone,
        attempt_type varchar(20) not null,
        ip_address varchar(45),
        username varchar(50),
        primary key (id)
    );

    create table notification (
        created_at timestamp(6) with time zone not null,
        delivered_at timestamp(6) with time zone,
        dismissed_at timestamp(6) with time zone,
        expires_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        read_at timestamp(6) with time zone,
        recipient_id bigint not null,
        scheduled_for timestamp(6) with time zone,
        sent_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        priority varchar(10) not null check (priority in ('LOW','NORMAL','HIGH','URGENT')),
        status varchar(15) not null check (status in ('PENDING','SENT','DELIVERED','FAILED','READ','DISMISSED')),
        type varchar(20) not null check (type in ('REMINDER','CONFIRMATION','ALERT','SECURITY','SOCIAL','INFO','SYSTEM')),
        source_reference_id varchar(36),
        created_by varchar(50),
        source_domain varchar(50),
        updated_by varchar(50),
        icon varchar(100),
        title varchar(150) not null,
        public_id varchar(256) unique,
        body varchar(500),
        action_url varchar(255),
        data TEXT,
        primary key (id)
    );

    create table notification_channel (
        notification_id bigint not null,
        channel varchar(10) check (channel in ('IN_APP','EMAIL','PUSH','SMS'))
    );

    create table notification_preference (
        digest_enabled boolean,
        enabled boolean not null,
        quiet_hours_end time(6),
        quiet_hours_start time(6),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        channel varchar(10) not null check (channel in ('IN_APP','EMAIL','PUSH','SMS')),
        digest_frequency varchar(10) check (digest_frequency in ('DAILY','WEEKLY')),
        notification_type varchar(20) not null check (notification_type in ('REMINDER','CONFIRMATION','ALERT','SECURITY','SOCIAL','INFO','SYSTEM')),
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        primary key (id),
        constraint uk_notification_pref_user_type_channel unique (user_id, notification_type, channel)
    );

    create table oauth_account (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        token_expires_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        created_by varchar(50),
        provider varchar(50) not null check (provider in ('GITHUB','GOOGLE','MICROSOFT')),
        updated_by varchar(50),
        email varchar(254),
        public_id varchar(256) unique,
        access_token varchar(1000),
        refresh_token varchar(1000),
        provider_user_id varchar(255) not null,
        primary key (id),
        constraint uk_oauth_provider_user_id unique (provider, provider_user_id)
    );

    create table organisation_tag (
        organisation_id bigint not null,
        tag_id bigint not null,
        primary key (organisation_id, tag_id)
    );

    create table password_history (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        created_by varchar(50),
        updated_by varchar(50),
        password_hash varchar(72) not null,
        public_id varchar(256) unique,
        primary key (id)
    );

    create table password_reset_token (
        id bigint not null,
        primary key (id)
    );

    create table refresh_token (
        device_id bigint,
        id bigint not null,
        primary key (id)
    );

    create table sport_track (
        avg_speed_mps float(53),
        bounds_max_lat float(53),
        bounds_max_lon float(53),
        bounds_min_lat float(53),
        bounds_min_lon float(53),
        distance_meters float(53) not null,
        elevation_gain float(53),
        elevation_loss float(53),
        elevation_max float(53),
        elevation_min float(53),
        max_speed_mps float(53),
        total_track_points integer not null,
        created_at timestamp(6) with time zone not null,
        duration_seconds bigint not null,
        ended_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        started_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        sport_type varchar(50) not null check (sport_type in ('MTB','CYCLING','RUNNING','TRAIL_RUNNING','HIKING','WALKING','OTHER')),
        updated_by varchar(50),
        gpx_file_public_id varchar(256) not null,
        owner_public_id varchar(256) not null,
        public_id varchar(256) unique,
        name varchar(255) not null,
        elevation_profile oid,
        simplified_track oid,
        primary key (id)
    );

    create table stored_file (
        image_height integer,
        image_width integer,
        created_at timestamp(6) with time zone not null,
        deleted_at timestamp(6) with time zone,
        file_size bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        extension varchar(20),
        status varchar(20) not null check (status in ('PENDING','ACTIVE','ARCHIVED','DELETED')),
        category varchar(30) not null check (category in ('AVATAR','DOCUMENT','PRODUCT_IMAGE','TEMPORARY','GPX_TRACK')),
        created_by varchar(50),
        owner_type varchar(50) not null,
        updated_by varchar(50),
        checksum varchar(64),
        content_type varchar(100) not null,
        stored_filename varchar(100) not null,
        owner_public_id varchar(256) not null,
        public_id varchar(256) unique,
        description varchar(500),
        storage_path varchar(500) not null,
        original_filename varchar(255) not null,
        primary key (id)
    );

    create table two_factor_auth (
        enabled boolean not null,
        failed_attempts integer not null,
        is_primary boolean not null,
        remaining_backup_codes integer not null,
        created_at timestamp(6) with time zone not null,
        disabled_at timestamp(6) with time zone,
        enabled_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_verified_at timestamp(6) with time zone,
        locked_until timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        type varchar(20) not null check (type in ('TOTP','SMS','EMAIL','BACKUP_CODES','WEBAUTHN')),
        created_by varchar(50),
        updated_by varchar(50),
        label varchar(100),
        email_address varchar(200),
        phone_number varchar(200),
        public_id varchar(256) unique,
        secret varchar(500),
        backup_codes_hashed varchar(2000),
        primary key (id),
        constraint uk_user_type unique (user_id, type)
    );

    create table user_ (
        email_verified boolean not null,
        enabled boolean not null,
        ever_activated boolean not null,
        must_change_password boolean not null,
        phone_number_verified boolean not null,
        profile_complete boolean not null,
        two_factor_enabled boolean not null,
        activated_at timestamp(6) with time zone,
        activated_by bigint,
        admin_deactivated_at timestamp(6) with time zone,
        admin_deactivated_by bigint,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        gdpr_deleted_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        password_changed_at timestamp(6) with time zone,
        reactivated_at timestamp(6) with time zone,
        reactivated_by bigint,
        recovery_email_changed_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        created_by varchar(50),
        firstname varchar(50),
        lastname varchar(50),
        phone_number varchar(50),
        updated_by varchar(50),
        username varchar(50) not null unique,
        email varchar(254) not null unique,
        recovery_email varchar(254) unique,
        recovery_email_previous varchar(254),
        public_id varchar(256) unique,
        admin_deactivation_details varchar(500),
        avatar_url varchar(500),
        bio varchar(500),
        reason_details varchar(500),
        admin_deactivation_reason varchar(255) check (admin_deactivation_reason in ('BANNED_HATE_SPEECH','BANNED_HARASSMENT','BANNED_INAPPROPRIATE_BEHAVIOR','LEGAL_REQUEST','LEGAL_COPYRIGHT','LEGAL_MINOR_SAFETY','TOS_VIOLATION_SPAM','TOS_VIOLATION_MULTIPLE_ACCOUNTS','TOS_VIOLATION_COMMERCIAL_ABUSE','TOS_VIOLATION_UNDERAGE','TOS_VIOLATION_FRAUD','TOS_VIOLATION_IMPERSONATION','SECURITY_RISK_COMPROMISED_ACCOUNT','SECURITY_RISK_SUSPICIOUS_ACTIVITY','SECURITY_RISK_MALWARE','MAINTENANCE_SYSTEM_UPGRADE','MAINTENANCE_DATA_CLEANUP','MAINTENANCE_MIGRATION','ADMIN_ERROR','ADMIN_INVESTIGATION','OTHER_ADMIN_REASON')),
        deactivation_reason varchar(255) check (deactivation_reason in ('TAKING_A_BREAK','TOO_MUCH_TIME','PRIVACY_CONCERNS','ACCOUNT_CLEANUP','SWITCHING_ACCOUNTS','WORK_REQUIREMENTS','NOT_USEFUL','OTHER')),
        password varchar(255),
        reactivation_policy varchar(255) check (reactivation_policy in ('NEVER','SELF_SERVICE','ADMIN_ONLY','SUPER_ADMIN_ONLY')),
        primary key (id)
    );

    create table user_address (
        billing_eligible boolean not null,
        is_primary boolean not null,
        shipping_eligible boolean not null,
        id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table user_attempt (
        attempt_count integer not null,
        created_at timestamp(6) with time zone not null,
        device_id bigint,
        id bigint generated by default as identity,
        last_attempt_time timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        created_by varchar(50),
        updated_by varchar(50),
        public_id varchar(256) unique,
        attempt_type varchar(255) not null check (attempt_type in ('ACCOUNT_CONFIRMATION','ACCOUNT_DEACTIVATION','ACCOUNT_REACTIVATION','ACCOUNT_DELETION','DEVICE_CONFIRMATION','EMAIL_CONFIRMATION','EMAIL_PASSWORD_RESET','SMS_PASSWORD_RESET','EMAIL_2FA_ACTIVATION','EMAIL_2FA_VERIFICATION','TOTP_2FA_ACTIVATION','TOTP_2FA_VERIFICATION')),
        primary key (id),
        unique (user_id, attempt_type, device_id)
    );

    create table user_roles (
        user_id bigint not null,
        role varchar(255) check (role in ('MONITORING','SUPER_ADMIN','ADMIN','MODERATOR','COMMERCIAL','USER','GUEST'))
    );

    create table verification_code_token (
        id bigint not null,
        verification_code_hash varchar(60),
        primary key (id)
    );

    create index idx_log_public_id 
       on activity_log (public_id);

    create index idx_log_user_timestamp 
       on activity_log (user_id, timestamp);

    create index idx_log_action_type 
       on activity_log (action_type);

    create index idx_log_action_category 
       on activity_log (action_category);

    create index idx_address_postal_code 
       on address (postal_code);

    create index idx_address_city 
       on address (city);

    create index idx_address_country 
       on address (country_code);

    create index idx_address_link_address 
       on address_link (address_id);

    create index idx_address_link_type 
       on address_link (address_type);

    create index idx_address_link_default 
       on address_link (is_default);

    create index idx_user_revoked 
       on base_token (user_id, revoked);

    create index idx_expiry_revoked 
       on base_token (expiry_date, revoked);

    create index idx_user_token_type_revoked 
       on base_token (user_id, token_type, revoked);

    create index idx_token_type_expiry 
       on base_token (token_type, expiry_date);

    create index idx_public_id_type 
       on base_token (public_id, token_type);

    create index idx_public_id_revoked 
       on base_token (public_id, revoked);

    create index idx_calendar_event_public_id 
       on calendar_event (public_id);

    create index idx_calendar_event_owner 
       on calendar_event (owner_public_id);

    create index idx_calendar_event_start 
       on calendar_event (start_date_time);

    create index idx_calendar_event_status 
       on calendar_event (status);

    create index idx_calendar_event_address 
       on calendar_event (address_id);

    create index idx_calendar_event_source 
       on calendar_event (source_public_id);

    create index idx_CommercialAction_public_id 
       on commercial_action (public_id);

    create index idx_CommercialAction_assigned 
       on commercial_action (assigned_to_id);

    create index idx_CommercialAction_deal 
       on commercial_action (deal_id);

    create index idx_CommercialAction_contact 
       on commercial_action (contact_id);

    create index idx_CommercialAction_lead 
       on commercial_action (lead_id);

    create index idx_CommercialAction_status 
       on commercial_action (status);

    create index idx_CommercialAction_due 
       on commercial_action (due_date);

    create index idx_CommercialAction_reminder 
       on commercial_action (reminder_at);

    create index idx_CommercialAction_address 
       on commercial_action (address_id);

    create index idx_calllog_interaction 
       on crm_call_log (interaction_id);

    create index idx_crm_cl_public_id 
       on crm_change_log (public_id);

    create index idx_crm_cl_entity 
       on crm_change_log (entity_type, entity_public_id);

    create index idx_crm_cl_changed_at 
       on crm_change_log (changed_at);

    create index idx_contact_public_id 
       on crm_contact (public_id);

    create index idx_contact_email 
       on crm_contact (email);

    create index idx_contact_org 
       on crm_contact (organisation_id);

    create index idx_contact_assigned 
       on crm_contact (assigned_to_id);

    create index idx_contact_status 
       on crm_contact (status);

    create index idx_deal_public_id 
       on crm_deal (public_id);

    create index idx_deal_stage 
       on crm_deal (stage_id);

    create index idx_deal_assigned 
       on crm_deal (assigned_to_id);

    create index idx_deal_status 
       on crm_deal (status);

    create index idx_emaillog_interaction 
       on crm_email_log (interaction_id);

    create index idx_emaillog_external_id 
       on crm_email_log (external_message_id);

    create index idx_interaction_public_id 
       on crm_interaction (public_id);

    create index idx_interaction_deal 
       on crm_interaction (deal_id);

    create index idx_interaction_contact 
       on crm_interaction (contact_id);

    create index idx_interaction_lead 
       on crm_interaction (lead_id);

    create index idx_interaction_user 
       on crm_interaction (performed_by_id);

    create index idx_interaction_occurred 
       on crm_interaction (occurred_at);

    create index idx_org_public_id 
       on crm_organisation (public_id);

    create index idx_org_name 
       on crm_organisation (name);

    create index idx_pipeline_public_id 
       on crm_pipeline (public_id);

    create index idx_pipeline_default 
       on crm_pipeline (is_default);

    create index idx_pipeline_step_public_id 
       on crm_pipeline_step (public_id);

    create index idx_pipeline_step_pipeline 
       on crm_pipeline_step (pipeline_id);

    create index idx_ticket_public_id 
       on crm_support_ticket (public_id);

    create index idx_ticket_contact 
       on crm_support_ticket (submitted_by_id);

    create index idx_ticket_assigned 
       on crm_support_ticket (assigned_to_id);

    create index idx_ticket_status 
       on crm_support_ticket (status);

    create index idx_dcr_deal 
       on deal_contact_role (deal_id);

    create index idx_dcr_contact 
       on deal_contact_role (contact_id);

    create index idx_dsh_deal 
       on deal_stage_history (deal_id);

    create index idx_dsh_step 
       on deal_stage_history (pipeline_step_id);

    create index idx_failed_email_status 
       on failed_email (status);

    create index idx_failed_email_next_retry 
       on failed_email (next_retry_at);

    create index idx_failed_email_status_retry 
       on failed_email (status, next_retry_at);

    create index idx_failed_geocoding_status 
       on failed_geocoding (status);

    create index idx_failed_geocoding_address_id 
       on failed_geocoding (address_id);

    create index idx_failed_sms_status 
       on failed_sms (status);

    create index idx_failed_sms_next_retry 
       on failed_sms (next_retry_at);

    create index idx_failed_sms_status_retry 
       on failed_sms (status, next_retry_at);

    create index idx_gdpr_export_user 
       on gdpr_export_request (user_id);

    create index idx_gdpr_export_status 
       on gdpr_export_request (status);

    create index idx_gdpr_export_expires_at 
       on gdpr_export_request (expires_at);

    create index idx_lead_email 
       on lead (email);

    create index idx_lead_submitted_at 
       on lead (submitted_at);

    create index idx_lead_type 
       on lead (lead_type);

    create index idx_lead_ip 
       on lead (ip_address);

    create index idx_lead_status 
       on lead (status);

    create index idx_lead_assigned 
       on lead (assigned_to_id);

    create index idx_login_attempt_username 
       on login_attempt (username);

    create index idx_login_attempt_ip 
       on login_attempt (ip_address);

    create index idx_login_attempt_combo 
       on login_attempt (username, ip_address);

    create index idx_notification_recipient 
       on notification (recipient_id);

    create index idx_notification_recipient_status 
       on notification (recipient_id, status);

    create index idx_notification_recipient_read 
       on notification (recipient_id, read_at);

    create index idx_notification_type 
       on notification (type);

    create index idx_notification_created 
       on notification (created_at);

    create index idx_notification_pref_user 
       on notification_preference (user_id);

    create index idx_notification_pref_user_type 
       on notification_preference (user_id, notification_type);

    create index idx_oauth_user_id 
       on oauth_account (user_id);

    create index idx_oauth_provider_email 
       on oauth_account (provider, email);

    create index idx_password_history_user 
       on password_history (user_id);

    create index idx_password_history_user_created 
       on password_history (user_id, created_at);

    create index idx_sport_track_public_id 
       on sport_track (public_id);

    create index idx_sport_track_owner 
       on sport_track (owner_public_id);

    create index idx_sport_track_type 
       on sport_track (sport_type);

    create index idx_sport_track_started_at 
       on sport_track (started_at);

    create index idx_stored_file_public_id 
       on stored_file (public_id);

    create index idx_stored_file_owner 
       on stored_file (owner_public_id);

    create index idx_stored_file_category 
       on stored_file (category);

    create index idx_stored_file_status 
       on stored_file (status);

    create index idx_tfa_user_enabled
       on two_factor_auth (user_id, enabled);

    create index idx_type 
       on two_factor_auth (type);

    create index idx_user_public_id 
       on user_ (public_id);

    create index idx_user_email 
       on user_ (email);

    create index idx_user_username 
       on user_ (username);

    create index idx_user_enabled 
       on user_ (enabled);

    create index idx_user_address_user 
       on user_address (user_id);

    alter table if exists account_confirmation_token 
       add constraint FKhpqc3rwtwvxe07phil3j93vr7 
       foreign key (id) 
       references base_token;

    alter table if exists account_deactivation_token 
       add constraint FK9kmn46e3ua5po9piwkym0j1v7 
       foreign key (id) 
       references base_token;

    alter table if exists account_deletion_token 
       add constraint FK4l0wsfgjr13qh1t7mi3y1ejkx 
       foreign key (id) 
       references base_token;

    alter table if exists account_reactivation_token 
       add constraint FK2kod4icufcnbfjakfhkphp4u5 
       foreign key (id) 
       references base_token;

    alter table if exists activity_log 
       add constraint FKhdegiqtcrrka8d2xxymlvb8wq 
       foreign key (device_id) 
       references devices;

    alter table if exists activity_log 
       add constraint FKix3xq523ei00qtdypnera7ml9 
       foreign key (target_device_id) 
       references devices;

    alter table if exists activity_log 
       add constraint FKt4epf6c8ftt8ybfm96xauwcqi 
       foreign key (user_id) 
       references user_;

    alter table if exists address_link 
       add constraint FKn5epaqp2calh6hl8kqih4wmrw 
       foreign key (address_id) 
       references address;

    alter table if exists base_token 
       add constraint FKbndo7149xbosehwhboembmax7 
       foreign key (user_id) 
       references user_;

    alter table if exists calendar_event 
       add constraint FKfmvhyor9pdp24tw2wr8y1n4m2 
       foreign key (address_id) 
       references address;

    alter table if exists commercial_action 
       add constraint FKs4gool1mpwpbbitohvs26fs4s 
       foreign key (address_id) 
       references address;

    alter table if exists commercial_action 
       add constraint FKr4k9f8td61dt047bk8fmoglyx 
       foreign key (assigned_to_id) 
       references user_;

    alter table if exists commercial_action 
       add constraint FKi62vjcn6p6gx922t5d0rju38r 
       foreign key (contact_id) 
       references crm_contact;

    alter table if exists commercial_action 
       add constraint FK3847roek1bjed3yaa43m7x751 
       foreign key (deal_id) 
       references crm_deal;

    alter table if exists commercial_action 
       add constraint FK8jv0m6uwi4bldfdjl6750vjao 
       foreign key (lead_id) 
       references lead;

    alter table if exists contact_tag 
       add constraint FKh4gqdmgdegcww1qbwc638vxlg 
       foreign key (tag_id) 
       references crm_tag;

    alter table if exists contact_tag 
       add constraint FKbbqhd4vwlq4ed0ldwxntofj8t 
       foreign key (contact_id) 
       references crm_contact;

    alter table if exists crm_call_log 
       add constraint FK8q4g41k0n7c8sr9beedld6aqa 
       foreign key (interaction_id) 
       references crm_interaction;

    alter table if exists crm_change_log 
       add constraint FKgbqestifysjxr1ckynm3xt9yf 
       foreign key (changed_by_id) 
       references user_;

    alter table if exists crm_contact 
       add constraint FKg9x408uyy7fc0q1emcjc8d63q 
       foreign key (assigned_to_id) 
       references user_;

    alter table if exists crm_contact 
       add constraint FK22gdc26gc4qtfalwfmljpd15a 
       foreign key (user_id) 
       references user_;

    alter table if exists crm_contact 
       add constraint FK9wfta3vltff478ehcv0hdbrqx 
       foreign key (organisation_id) 
       references crm_organisation;

    alter table if exists crm_contact 
       add constraint FK9igvy7usscqjj9xjo27shmy3s 
       foreign key (lead_id) 
       references lead;

    alter table if exists crm_deal 
       add constraint FKksqujviww9i8al385o7ybko01 
       foreign key (assigned_to_id) 
       references user_;

    alter table if exists crm_deal 
       add constraint FK52k2nhnxhh9gdxs85yu46qb73 
       foreign key (organisation_id) 
       references crm_organisation;

    alter table if exists crm_deal 
       add constraint FK83qc5wkrmlanauu9dh55kyu34 
       foreign key (pipeline_id) 
       references crm_pipeline;

    alter table if exists crm_deal 
       add constraint FKhapcct0a4djh2rxhsp7so3r53 
       foreign key (stage_id) 
       references crm_pipeline_step;

    alter table if exists crm_email_log 
       add constraint FKgo6q484fhjndbcvsts93q8do3 
       foreign key (interaction_id) 
       references crm_interaction;

    alter table if exists crm_interaction 
       add constraint FKf02xd4rju8b0qqf9vrawto76e 
       foreign key (contact_id) 
       references crm_contact;

    alter table if exists crm_interaction 
       add constraint FKtqix0qs3grh5k9312uffj8v9o 
       foreign key (deal_id) 
       references crm_deal;

    alter table if exists crm_interaction 
       add constraint FKglmh891smp0h279t2ea1k30vp 
       foreign key (lead_id) 
       references lead;

    alter table if exists crm_interaction 
       add constraint FKi6gq89ci5f5yyvbfari0lqxyk 
       foreign key (performed_by_id) 
       references user_;

    alter table if exists crm_organisation 
       add constraint FKnihix6g123ge0fxshorq4h6dk 
       foreign key (address_id) 
       references address;

    alter table if exists crm_pipeline_step 
       add constraint FK3fis55oxclfdrp3ljl0t5ql8g 
       foreign key (pipeline_id) 
       references crm_pipeline;

    alter table if exists crm_support_ticket 
       add constraint FKppe2bjnwxjk8k34o7ox84jfct 
       foreign key (assigned_to_id) 
       references user_;

    alter table if exists crm_support_ticket 
       add constraint FKstc7knyp78q4n0jq92afbwhrm 
       foreign key (submitted_by_id) 
       references crm_contact;

    alter table if exists deal_contact_role 
       add constraint FKd3qvor4tj390kkgrq30gsq5b8 
       foreign key (contact_id) 
       references crm_contact;

    alter table if exists deal_contact_role 
       add constraint FK81dn1tc187v3ewj5e05kwcp64 
       foreign key (deal_id) 
       references crm_deal;

    alter table if exists deal_stage_history 
       add constraint FK1qnr589lxaj641nnx8ex77ixy 
       foreign key (deal_id) 
       references crm_deal;

    alter table if exists deal_stage_history 
       add constraint FK63vxrfapmikpmmmgbm4g1mx4c 
       foreign key (pipeline_step_id) 
       references crm_pipeline_step;

    alter table if exists deal_tag 
       add constraint FKa4xbtq1oa40i2n1da6fwbcyrq 
       foreign key (tag_id) 
       references crm_tag;

    alter table if exists deal_tag 
       add constraint FKpoum8ew2n98nqb1fusng9myqd 
       foreign key (deal_id) 
       references crm_deal;

    alter table if exists device_confirmation_token 
       add constraint FKojdhilyh107iviyyprtss10nt 
       foreign key (id) 
       references base_token;

    alter table if exists devices 
       add constraint FKq2ylybvge2nfmkjebi2js5591 
       foreign key (user_id) 
       references user_;

    alter table if exists email_confirmation_token 
       add constraint FKu1gdmq893fmo1in60dblnttk 
       foreign key (id) 
       references base_token;

    alter table if exists failed_geocoding 
       add constraint FKmbbt2n03vxla9kop2ndrw5o0d 
       foreign key (address_id) 
       references address;

    alter table if exists gdpr_export_request 
       add constraint FK3y8ed2i77mhiav25o5y1u0gf 
       foreign key (user_id) 
       references user_;

    alter table if exists lead 
       add constraint FK77hsifsnj7q5rlxcoi1kkbax7 
       foreign key (assigned_to_id) 
       references user_;

    alter table if exists lead_tag 
       add constraint FKfn621vhewoly3c41q4h3pjwkk 
       foreign key (tag_id) 
       references crm_tag;

    alter table if exists lead_tag 
       add constraint FK774ir1xtyh6x71kvf5uxrc0l2 
       foreign key (lead_id) 
       references lead;

    alter table if exists notification 
       add constraint FK3jq3tpav8ub79pwhdqg90a1ak 
       foreign key (recipient_id) 
       references user_;

    alter table if exists notification_channel 
       add constraint FKe6y32pwi3mivm49cdlg1elakm 
       foreign key (notification_id) 
       references notification;

    alter table if exists notification_preference 
       add constraint FKn1kj920qmgjugmsxbrimk6ay2 
       foreign key (user_id) 
       references user_;

    alter table if exists oauth_account 
       add constraint FK46nwv7vt8ptutpb3673ngmejc 
       foreign key (user_id) 
       references user_;

    alter table if exists organisation_tag 
       add constraint FK44i7b9jvqe4b3abues7ttdqf9 
       foreign key (tag_id) 
       references crm_tag;

    alter table if exists organisation_tag 
       add constraint FK61e8phw4r6u03vs3k0hajykqd 
       foreign key (organisation_id) 
       references crm_organisation;

    alter table if exists password_history 
       add constraint FKmhckscsx5r6rdpg5rw3cmqrsc 
       foreign key (user_id) 
       references user_;

    alter table if exists password_reset_token 
       add constraint FK7v6bp2t7xym5ynlakdimw2b86 
       foreign key (id) 
       references base_token;

    alter table if exists refresh_token 
       add constraint FKk50xogforck8giwxyhvtio9wt 
       foreign key (device_id) 
       references devices;

    alter table if exists refresh_token 
       add constraint FKopeq02frl680gbuj5264rt91q 
       foreign key (id) 
       references base_token;

    alter table if exists two_factor_auth 
       add constraint FKe0pk1hi2jyt7h8u9vahybr4t4 
       foreign key (user_id) 
       references user_;

    alter table if exists user_ 
       add constraint FKg53v3vb0jxv0mc6n0ks2vykpm 
       foreign key (activated_by) 
       references user_;

    alter table if exists user_ 
       add constraint FK1psvhgsb6gh9jqqx2aj18ex9w 
       foreign key (admin_deactivated_by) 
       references user_;

    alter table if exists user_ 
       add constraint FKjxs1bp1o19g36n2p4mfpolgqk 
       foreign key (reactivated_by) 
       references user_;

    alter table if exists user_address 
       add constraint FKkaj529agu62ts5wnvmt0ir9le 
       foreign key (user_id) 
       references user_;

    alter table if exists user_address 
       add constraint FK6fgt2jfhsdj2bb1w0hb6tp75w 
       foreign key (id) 
       references address_link;

    alter table if exists user_attempt 
       add constraint FKlx7wkka3uuw5efvik0atmf3x2 
       foreign key (user_id) 
       references user_;

    alter table if exists user_roles 
       add constraint FKi11ca3b26vh3bcucnq39inil3 
       foreign key (user_id) 
       references user_;

    alter table if exists verification_code_token 
       add constraint FKd3kyo6hp5dpvo9pirmw1mu4ck 
       foreign key (id) 
       references base_token;
