-- ============================================================
-- V2 — CRM telephony integration
-- Tables: crm_call_session, crm_telephony_config
-- ============================================================

    -- ----------------------------------------------------------
    -- crm_call_session
    -- Tracks the technical lifecycle of an outbound call.
    -- Linked to crm_interaction + crm_call_log once terminated.
    -- ----------------------------------------------------------

    create table crm_call_session (
        duration_seconds  integer,
        answered_at       timestamp(6) with time zone,
        contact_id        bigint,
        created_at        timestamp(6) with time zone not null,
        ended_at          timestamp(6) with time zone,
        id                bigint generated by default as identity,
        lead_id           bigint,
        performed_by_id   bigint not null,
        started_at        timestamp(6) with time zone not null,
        updated_at        timestamp(6) with time zone not null,
        provider          varchar(15) not null check (provider in ('TEL_URI','TWILIO','SIP')),
        status            varchar(15) not null check (status in ('INITIATED','RINGING','ACTIVE','ENDED','FAILED','MISSED')),
        created_by        varchar(50),
        updated_by        varchar(50),
        phone_number      varchar(30) not null,
        external_call_id  varchar(100),
        public_id         varchar(256) unique,
        primary key (id)
    );

    -- ----------------------------------------------------------
    -- crm_telephony_config
    -- Per-tenant telephony provider configuration.
    -- Only one record should have active = true at a time.
    -- ----------------------------------------------------------

    create table crm_telephony_config (
        active                boolean not null,
        created_at            timestamp(6) with time zone not null,
        id                    bigint generated by default as identity,
        updated_at            timestamp(6) with time zone not null,
        provider              varchar(15) not null check (provider in ('TEL_URI','TWILIO','SIP')),
        created_by            varchar(50),
        updated_by            varchar(50),
        caller_id             varchar(30),
        public_id             varchar(256) unique,
        encrypted_credentials text,
        primary key (id)
    );

    -- ----------------------------------------------------------
    -- Indexes — crm_call_session
    -- ----------------------------------------------------------

    create index idx_callsession_public_id
        on crm_call_session (public_id);

    create index idx_callsession_contact
        on crm_call_session (contact_id);

    create index idx_callsession_lead
        on crm_call_session (lead_id);

    create index idx_callsession_user
        on crm_call_session (performed_by_id);

    create index idx_callsession_status
        on crm_call_session (status);

    -- ----------------------------------------------------------
    -- Indexes — crm_telephony_config
    -- ----------------------------------------------------------

    create index idx_telephonyconfig_provider
        on crm_telephony_config (provider);

    create index idx_telephonyconfig_active
        on crm_telephony_config (active);

    -- ----------------------------------------------------------
    -- Foreign keys — crm_call_session
    -- ----------------------------------------------------------

    alter table if exists crm_call_session
        add constraint fk_callsession_contact
        foreign key (contact_id)
        references crm_contact;

    alter table if exists crm_call_session
        add constraint fk_callsession_lead
        foreign key (lead_id)
        references lead;

    alter table if exists crm_call_session
        add constraint fk_callsession_performed_by
        foreign key (performed_by_id)
        references user_;
