-- ============================================================
-- V3 — Per-commercial SIP extension credentials
-- Table: crm_commercial_sip_config
-- ============================================================

create table crm_commercial_sip_config (
    id                      bigint generated by default as identity,
    user_id                 bigint        not null unique,
    sip_username            varchar(100)  not null,
    encrypted_sip_password  text          not null,
    display_name            varchar(100),
    public_id               varchar(256)  unique,
    created_by              varchar(50),
    created_at              timestamp(6) with time zone not null,
    updated_by              varchar(50),
    updated_at              timestamp(6) with time zone not null,
    primary key (id)
);

alter table crm_commercial_sip_config
    add constraint fk_sip_config_user
    foreign key (user_id)
    references user_(id)
    on delete cascade;

create index idx_commercial_sip_config_user     on crm_commercial_sip_config (user_id);
create index idx_commercial_sip_config_public_id on crm_commercial_sip_config (public_id);
create unique index idx_commercial_sip_username   on crm_commercial_sip_config (sip_username);
