package be.steby.CoreProject.dal;

import be.steby.CoreProject.dl.entities.CalendarEvent;
import be.steby.CoreProject.dl.enums.EventStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for {@link CalendarEvent} entity persistence operations.
 * 
 * <p>Extends Spring Data JPA's {@link JpaRepository} to provide standard CRUD
 * operations plus custom query methods for calendar-specific use cases.</p>
 * 
 * <h3>Provided Operations</h3>
 * <p><b>From JpaRepository:</b></p>
 * <ul>
 *   <li>{@code save(CalendarEvent)} - Create or update</li>
 *   <li>{@code findById(Long)} - Find by internal ID</li>
 *   <li>{@code findAll()} - Retrieve all events</li>
 *   <li>{@code delete(CalendarEvent)} - Permanently delete</li>
 *   <li>{@code count()} - Count all events</li>
 * </ul>
 * 
 * <p><b>Custom Queries:</b></p>
 * <ul>
 *   <li>Find by public ID (API-safe identifier)</li>
 *   <li>Find all events for a user</li>
 *   <li>Find events within date range</li>
 *   <li>Find upcoming events only</li>
 *   <li>Filter by status</li>
 * </ul>
 * 
 * <h3>Query Performance</h3>
 * <p>All queries are optimized with appropriate database indexes:</p>
 * <ul>
 *   <li>{@code idx_calendar_event_public_id} - Fast public ID lookups</li>
 *   <li>{@code idx_calendar_event_owner} - Fast user event retrieval</li>
 *   <li>{@code idx_calendar_event_start} - Fast date range queries</li>
 *   <li>{@code idx_calendar_event_status} - Fast status filtering</li>
 * </ul>
 * 
 * <h3>Transaction Management</h3>
 * <p>Repository methods are automatically wrapped in transactions by Spring.
 * For custom transactional behavior, use {@code @Transactional} at the
 * service layer.</p>
 * 
 * <h3>Example Usage</h3>
 * <pre>{@code
 * @Service
 * public class CalendarService {
 *     private final CalendarEventRepository repository;
 *     
 *     public List<CalendarEvent> getUpcoming(String userPublicId) {
 *         return repository.findUpcomingEvents(
 *             userPublicId, 
 *             Instant.now()
 *         );
 *     }
 * }
 * }</pre>
 * 
 * @see CalendarEvent
 * @see JpaRepository
 * @author Steby Corp
 * @version 1.0
 * @since 1.0
 */
@Repository
public interface CalendarEventRepository extends JpaRepository<CalendarEvent, Long> {

    // =========================================================================
    // Public ID Queries (API-Safe)
    // =========================================================================

    /**
     * Finds a calendar event by its public ID.
     * 
     * <p>Public IDs are UUIDs generated by {@link be.steby.CoreProject.dl.entities.BaseEntity}
     * and are safe to expose in APIs. This is the preferred method for looking
     * up events from API requests.</p>
     * 
     * <p><b>Performance:</b> O(1) lookup via {@code idx_calendar_event_public_id} index</p>
     * 
     * <p><b>Security:</b> Public IDs are unpredictable, preventing enumeration attacks</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * Optional<CalendarEvent> event = repository.findByPublicId(
     *     "550e8400-e29b-41d4-a716-446655440000"
     * );
     * }</pre>
     * 
     * @param publicId The public UUID identifier of the event
     * @return Optional containing the event if found, empty otherwise
     * @throws IllegalArgumentException if publicId is null
     * @see CalendarEvent#getPublicId()
     */
    Optional<CalendarEvent> findByPublicId(String publicId);

    // =========================================================================
    // User-Specific Queries
    // =========================================================================

    /**
     * Finds all events belonging to a specific user, ordered by start date ascending.
     * 
     * <p>Returns all events (past, present, and future) for the given user.
     * Events are sorted chronologically by start date, making it easy to
     * display in timeline views.</p>
     * 
     * <p><b>Performance:</b> Indexed query on {@code owner_public_id} column</p>
     * 
     * <p><b>Use Cases:</b></p>
     * <ul>
     *   <li>User's complete calendar view</li>
     *   <li>Event history and archive</li>
     *   <li>Export all user events to .ics</li>
     * </ul>
     * 
     * <p><b>Note:</b> Includes CANCELLED events. Filter at service layer if needed.</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * List<CalendarEvent> allEvents = repository.findByOwnerPublicId(
     *     user.getPublicId()
     * );
     * }</pre>
     * 
     * @param ownerPublicId The public ID of the user who owns the events
     * @return List of events sorted by start date (empty list if none found)
     * @throws IllegalArgumentException if ownerPublicId is null
     */
    @Query("SELECT e FROM CalendarEvent e WHERE e.ownerPublicId = :ownerPublicId ORDER BY e.startDateTime ASC")
    List<CalendarEvent> findByOwnerPublicId(@Param("ownerPublicId") String ownerPublicId);

    /**
     * Finds events for a user within a specific date range.
     * 
     * <p>Retrieves events where BOTH start and end times fall within the
     * specified date range. Useful for calendar month/week/day views where
     * you need to show only relevant events.</p>
     * 
     * <p><b>Date Range Logic:</b></p>
     * <ul>
     *   <li>Event starts at or after {@code startDate}</li>
     *   <li>Event ends at or before {@code endDate}</li>
     *   <li>Events sorted by start date ascending</li>
     * </ul>
     * 
     * <p><b>Performance:</b> Compound index on (owner_public_id, start_date_time)</p>
     * 
     * <p><b>Use Cases:</b></p>
     * <ul>
     *   <li>Calendar month view (Feb 1-28)</li>
     *   <li>Calendar week view (Mon-Sun)</li>
     *   <li>Calendar day view (00:00-23:59)</li>
     *   <li>Date range reports</li>
     * </ul>
     * 
     * <p><b>Note:</b> Includes CANCELLED events. Filter at service layer if needed.</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * // Get all events in February 2025
     * Instant start = Instant.parse("2025-02-01T00:00:00Z");
     * Instant end = Instant.parse("2025-02-28T23:59:59Z");
     * 
     * List<CalendarEvent> februaryEvents = repository.findByOwnerAndDateRange(
     *     user.getPublicId(),
     *     start,
     *     end
     * );
     * }</pre>
     * 
     * @param ownerPublicId The public ID of the event owner
     * @param startDate Start of the date range (inclusive)
     * @param endDate End of the date range (inclusive)
     * @return List of events within the range, sorted by start date
     * @throws IllegalArgumentException if any parameter is null
     */
    @Query("SELECT e FROM CalendarEvent e WHERE e.ownerPublicId = :ownerPublicId " +
           "AND e.startDateTime >= :startDate AND e.endDateTime <= :endDate " +
           "ORDER BY e.startDateTime ASC")
    List<CalendarEvent> findByOwnerAndDateRange(
        @Param("ownerPublicId") String ownerPublicId,
        @Param("startDate") Instant startDate,
        @Param("endDate") Instant endDate
    );

    /**
     * Finds upcoming events for a user (future events only, excluding cancelled).
     * 
     * <p>Retrieves events that:</p>
     * <ul>
     *   <li>Start at or after the specified time (typically now)</li>
     *   <li>Are not cancelled (status != CANCELLED)</li>
     *   <li>Sorted chronologically by start date</li>
     * </ul>
     * 
     * <p><b>Performance:</b> Compound index on (owner_public_id, start_date_time, status)</p>
     * 
     * <p><b>Use Cases:</b></p>
     * <ul>
     *   <li>"What's next" dashboard widget</li>
     *   <li>Upcoming events list</li>
     *   <li>Reminder notification system</li>
     *   <li>Calendar preview/summary</li>
     * </ul>
     * 
     * <p><b>Important:</b> CANCELLED events are automatically excluded.
     * This is the most commonly used query for displaying active future events.</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * // Get all future events starting now
     * List<CalendarEvent> upcoming = repository.findUpcomingEvents(
     *     user.getPublicId(),
     *     Instant.now()
     * );
     * 
     * // Get events starting tomorrow
     * Instant tomorrow = Instant.now().plus(1, ChronoUnit.DAYS);
     * List<CalendarEvent> tomorrowEvents = repository.findUpcomingEvents(
     *     user.getPublicId(),
     *     tomorrow
     * );
     * }</pre>
     * 
     * @param ownerPublicId The public ID of the event owner
     * @param now The reference time point (typically {@code Instant.now()})
     * @return List of upcoming non-cancelled events, sorted by start date
     * @throws IllegalArgumentException if any parameter is null
     * @see EventStatus#CANCELLED
     */
    @Query("SELECT e FROM CalendarEvent e WHERE e.ownerPublicId = :ownerPublicId " +
           "AND e.startDateTime >= :now AND e.status != 'CANCELLED' " +
           "ORDER BY e.startDateTime ASC")
    List<CalendarEvent> findUpcomingEvents(
        @Param("ownerPublicId") String ownerPublicId,
        @Param("now") Instant now
    );

    // =========================================================================
    // Status-Based Queries
    // =========================================================================

    /**
     * Finds events for a user filtered by status.
     * 
     * <p>Retrieves all events with a specific status, useful for:</p>
     * <ul>
     *   <li>Showing only confirmed events</li>
     *   <li>Listing tentative events needing confirmation</li>
     *   <li>Finding cancelled events for audit</li>
     * </ul>
     * 
     * <p><b>Performance:</b> Compound index on (owner_public_id, status)</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * // Get all cancelled events for history
     * List<CalendarEvent> cancelled = repository.findByOwnerAndStatus(
     *     user.getPublicId(),
     *     EventStatus.CANCELLED
     * );
     * 
     * // Get tentative events needing confirmation
     * List<CalendarEvent> tentative = repository.findByOwnerAndStatus(
     *     user.getPublicId(),
     *     EventStatus.TENTATIVE
     * );
     * }</pre>
     * 
     * @param ownerPublicId The public ID of the event owner
     * @param status The status to filter by
     * @return List of events with the specified status, sorted by start date
     * @throws IllegalArgumentException if any parameter is null
     * @see EventStatus
     */
    @Query("SELECT e FROM CalendarEvent e WHERE e.ownerPublicId = :ownerPublicId " +
           "AND e.status = :status ORDER BY e.startDateTime ASC")
    List<CalendarEvent> findByOwnerAndStatus(
        @Param("ownerPublicId") String ownerPublicId,
        @Param("status") EventStatus status
    );

    // =========================================================================
    // Statistics & Counts
    // =========================================================================

    /**
     * Counts the total number of events for a user.
     * 
     * <p>Includes all events regardless of status (confirmed, tentative, cancelled)
     * or date (past, present, future).</p>
     * 
     * <p><b>Performance:</b> O(1) indexed count on {@code owner_public_id}</p>
     * 
     * <p><b>Use Cases:</b></p>
     * <ul>
     *   <li>User statistics dashboard</li>
     *   <li>Storage usage tracking</li>
     *   <li>Pagination metadata</li>
     * </ul>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * long totalEvents = repository.countByOwnerPublicId(user.getPublicId());
     * System.out.println("User has " + totalEvents + " events");
     * }</pre>
     * 
     * @param ownerPublicId The public ID of the event owner
     * @return The count of events (0 if none)
     * @throws IllegalArgumentException if ownerPublicId is null
     */
    long countByOwnerPublicId(String ownerPublicId);

    // =========================================================================
    // Delete Operations
    // =========================================================================

    /**
     * Permanently deletes an event by its public ID.
     * 
     * <p><b>Warning:</b> This is a hard delete operation. The event and all
     * its data will be permanently removed from the database with no recovery
     * option.</p>
     * 
     * <p><b>Best Practice:</b> For most use cases, consider using
     * {@link EventStatus#CANCELLED} instead to maintain audit trail.</p>
     * 
     * <p><b>Transaction:</b> This operation should be wrapped in a transaction
     * at the service layer to ensure consistency.</p>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * @Transactional
     * public void deleteEvent(String publicId) {
     *     // Verify ownership first
     *     CalendarEvent event = findByPublicId(publicId)
     *         .orElseThrow(() -> new EventNotFoundException(publicId));
     *     
     *     verifyOwnership(event, currentUser);
     *     
     *     // Permanent delete
     *     repository.deleteByPublicId(publicId);
     *     
     *     // Emit domain event for audit
     *     eventPublisher.publish(new EventDeletedEvent(event));
     * }
     * }</pre>
     * 
     * @param publicId The public ID of the event to delete
     * @throws IllegalArgumentException if publicId is null
     * @see EventStatus#CANCELLED
     */
    void deleteByPublicId(String publicId);

    // =========================================================================
    // Existence Checks
    // =========================================================================

    /**
     * Checks if an event exists and belongs to a specific user.
     * 
     * <p>Lightweight existence check that doesn't load the full entity.
     * Useful for permission validation before expensive operations.</p>
     * 
     * <p><b>Performance:</b> EXISTS query, does not load entity data</p>
     * 
     * <p><b>Use Cases:</b></p>
     * <ul>
     *   <li>Quick ownership validation</li>
     *   <li>Permission checks before update/delete</li>
     *   <li>API endpoint access control</li>
     * </ul>
     * 
     * <p><b>Example:</b></p>
     * <pre>{@code
     * // Verify user owns the event before allowing update
     * if (!repository.existsByPublicIdAndOwnerPublicId(eventId, user.getPublicId())) {
     *     throw new UnauthorizedException("You don't own this event");
     * }
     * 
     * // Proceed with update
     * event.setTitle(newTitle);
     * repository.save(event);
     * }</pre>
     * 
     * @param publicId The public ID of the event
     * @param ownerPublicId The public ID of the expected owner
     * @return {@code true} if event exists and belongs to owner, {@code false} otherwise
     * @throws IllegalArgumentException if any parameter is null
     */
    boolean existsByPublicIdAndOwnerPublicId(String publicId, String ownerPublicId);
}