package be.steby.CoreProject.bll.domains.contact.exceptions;

/**
 * Exception thrown when a contact creation or update is attempted
 * with an email address that is already registered to another contact.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Lead conversion — the lead's email already exists as a contact</li>
 *   <li>Manual contact creation — duplicate email detected</li>
 *   <li>Contact update — new email conflicts with an existing contact</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see ContactDomainException
 */
public class ContactEmailAlreadyExistsException extends ContactDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_EMAIL_ALREADY_EXISTS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public ContactEmailAlreadyExistsException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactEmailAlreadyExistsException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactEmailAlreadyExistsException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactEmailAlreadyExistsException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a duplicate email detected during contact creation.
     *
     * @param email the email address already registered to another contact
     * @return a new ContactEmailAlreadyExistsException
     */
    public static ContactEmailAlreadyExistsException forEmail(String email) {
        return new ContactEmailAlreadyExistsException(
                "A contact with email '" + email + "' already exists");
    }

    /**
     * Creates an exception for a duplicate email detected during lead conversion.
     *
     * @param email the lead email that conflicts with an existing contact
     * @return a new ContactEmailAlreadyExistsException
     */
    public static ContactEmailAlreadyExistsException fromLeadConversion(String email) {
        return new ContactEmailAlreadyExistsException(
                "Cannot convert lead: a contact with email '" + email + "' already exists");
    }
}