package be.steby.CoreProject.bll.domains.contact.exceptions;

import be.steby.CoreProject.dl.enums.crm.ContactStatus;

/**
 * Exception thrown when an invalid contact status transition is attempted.
 *
 * <p>The contact CRM lifecycle follows a defined flow:</p>
 * <pre>
 * NEW ──► ENGAGED ──► QUALIFIED ──► CLIENT
 *                                      │
 *              LOST ◄──────────────────┘ (if all deals lost)
 *              INACTIVE (no activity for a long period)
 * </pre>
 *
 * <p>This exception is raised when the service layer detects that
 * the requested transition is not allowed from the current status.</p>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see ContactDomainException
 * @see be.steby.CoreProject.dl.enums.crm.ContactStatus
 */
public class ContactStatusTransitionException extends ContactDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_STATUS_TRANSITION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public ContactStatusTransitionException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactStatusTransitionException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactStatusTransitionException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactStatusTransitionException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for an invalid transition between two statuses.
     *
     * @param from the current status of the contact
     * @param to   the requested target status
     * @return a new ContactStatusTransitionException
     */
    public static ContactStatusTransitionException invalidTransition(ContactStatus from, ContactStatus to) {
        return new ContactStatusTransitionException(
                "Invalid status transition from " + from.name() + " to " + to.name());
    }

    /**
     * Creates an exception for an invalid transition, including the contact's public UUID for traceability.
     *
     * @param publicId the public UUID of the contact
     * @param from     the current status of the contact
     * @param to       the requested target status
     * @return a new ContactStatusTransitionException
     */
    public static ContactStatusTransitionException invalidTransition(String publicId, ContactStatus from, ContactStatus to) {
        return new ContactStatusTransitionException(
                "Invalid status transition for contact '" + publicId + "': " + from.name() + " → " + to.name());
    }
}