package be.steby.CoreProject.bll.domains.contact.exceptions;

import java.util.List;

/**
 * Exception thrown when contact data fails business validation rules.
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Required field missing (first name, last name, email)</li>
 *   <li>Field value exceeding maximum allowed length</li>
 *   <li>Invalid email format</li>
 *   <li>Invalid phone number format</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 *
 * @see ContactDomainException
 */
public class ContactValidationException extends ContactDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     */
    public ContactValidationException(String message) {
        super(message, 400);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactValidationException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 400 (Bad Request).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactValidationException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactValidationException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception for a missing required field.
     *
     * @param fieldName the name of the missing field
     * @return a new ContactValidationException
     */
    public static ContactValidationException missingRequiredField(String fieldName) {
        return new ContactValidationException(
                "Required field is missing: " + fieldName);
    }

    /**
     * Creates an exception for multiple missing required fields.
     *
     * @param fieldNames the names of the missing fields
     * @return a new ContactValidationException
     */
    public static ContactValidationException missingRequiredFields(List<String> fieldNames) {
        return new ContactValidationException(
                "Required fields are missing: " + String.join(", ", fieldNames));
    }

    /**
     * Creates an exception for a field exceeding its maximum allowed length.
     *
     * @param fieldName the name of the field
     * @param maxLength the maximum allowed length
     * @param actual    the actual length provided
     * @return a new ContactValidationException
     */
    public static ContactValidationException fieldTooLong(String fieldName, int maxLength, int actual) {
        return new ContactValidationException(
                "Field '" + fieldName + "' exceeds maximum length of " + maxLength +
                " characters (actual: " + actual + ")");
    }

    /**
     * Creates an exception for an invalid email format.
     *
     * @param email the invalid email address
     * @return a new ContactValidationException
     */
    public static ContactValidationException invalidEmailFormat(String email) {
        return new ContactValidationException(
                "Invalid email format: '" + email + "'");
    }

    /**
     * Creates an exception for an invalid phone number format.
     *
     * @param phone the invalid phone number
     * @return a new ContactValidationException
     */
    public static ContactValidationException invalidPhoneFormat(String phone) {
        return new ContactValidationException(
                "Invalid phone number format: '" + phone + "'");
    }
}