package be.steby.CoreProject.bll.domains.contact.exceptions;

/**
 * Exception thrown when an attempt is made to link a platform account
 * to a contact that already has one.
 *
 * <p>A {@code Contact} can be linked to at most one {@code User} (platform account).
 * This link is established when the contact signs a contract and creates
 * an account on the platform. Once set, it cannot be overwritten.</p>
 *
 * <p>Typical scenarios:</p>
 * <ul>
 *   <li>Trying to link a {@code User} to a contact whose {@code linkedUser} is already populated</li>
 *   <li>Trying to link a {@code User} that is already linked to another contact</li>
 * </ul>
 *
 * <p>HTTP Status: 409 (Conflict)</p>
 *
 * @see ContactDomainException
 * @see be.steby.CoreProject.dl.entities.crm.Contact#hasLinkedUser()
 */
public class ContactAlreadyLinkedToUserException extends ContactDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CONTACT_ALREADY_LINKED_TO_USER";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    /**
     * Creates a new exception with a message.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     */
    public ContactAlreadyLinkedToUserException(String message) {
        super(message, 409);
    }

    /**
     * Creates a new exception with a message and status code.
     *
     * @param message the error message
     * @param status  the HTTP status code
     */
    public ContactAlreadyLinkedToUserException(String message, int status) {
        super(message, status);
    }

    /**
     * Creates a new exception with a message and cause.
     * Default status is 409 (Conflict).
     *
     * @param message the error message
     * @param cause   the underlying cause
     */
    public ContactAlreadyLinkedToUserException(String message, Throwable cause) {
        super(message, 409, cause);
    }

    /**
     * Creates a new exception with message, status, and cause.
     *
     * @param message the error message
     * @param status  the HTTP status code
     * @param cause   the underlying cause
     */
    public ContactAlreadyLinkedToUserException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    /**
     * Creates an exception when the contact already has a linked platform account.
     *
     * @param contactPublicId the public UUID of the contact
     * @return a new ContactAlreadyLinkedToUserException
     */
    public static ContactAlreadyLinkedToUserException contactAlreadyLinked(String contactPublicId) {
        return new ContactAlreadyLinkedToUserException(
                "Contact '" + contactPublicId + "' is already linked to a platform account");
    }

    /**
     * Creates an exception when the user is already linked to another contact.
     *
     * @param userPublicId the public UUID of the user
     * @return a new ContactAlreadyLinkedToUserException
     */
    public static ContactAlreadyLinkedToUserException userAlreadyLinked(String userPublicId) {
        return new ContactAlreadyLinkedToUserException(
                "User '" + userPublicId + "' is already linked to another contact");
    }
}