package be.steby.CoreProject.bll.common.exceptions;


public class AttributeUnchangedException extends CoreProjectException {



    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ATTRIBUTE_UNCHANGED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
  public AttributeUnchangedException(String message) {
    super(message,400);
  }
}
