package be.steby.CoreProject.bll.common.exceptions;

public class CurrentDeviceDisconnectionException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CURRENT_DEVICE_DISCONNECTION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public CurrentDeviceDisconnectionException(String message) {
        super(message, 400);
    }
}