package be.steby.CoreProject.bll.common.exceptions;


/**
 * Custom exception class to indicate that a requested resource does not exist.
 * This exception extends {@code BiobanqueException}, allowing for consistent handling
 * of exceptions specific to the BioBanque application.
 */
public class DoesntExistException extends CoreProjectException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "DOESNT_EXIST";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Constructs a new {@code DoesntExistException} with specified detail message and automatically assign
     * the HTTP status code 404.
     *
     * @param message the detail message to explaining the cause of exception.
     */
    public DoesntExistException(String message) {
        super(message,404);
    }
}
