package be.steby.CoreProject.bll.common.exceptions;

public class UserEnabledStatusException extends CoreProjectException {
    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "USER_ENABLED_STATUS";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Constructs a new {@code AuthenticationException} with the specified {@code detail message}.
     * The {@code status code} is set to {@code 403 (Unauthorized)} by default.
     *
     * @param message the detail message (which is saved for later retrieval
     *                by the {@link #getMessage()} method).
     */
    public UserEnabledStatusException(String message) {
        super(message, 403);
    }

    /**
     * Constructs a new {@code AuthenticationException} with the specified {@code detail message} and {@code status code}.
     *
     * @param message the {@code detail message} (which is saved for later retrieval
     *                by the {@link #getMessage()} method).
     * @param status  the {@code HTTP status code} (which is saved for later retrieval
     *                by the {@link #getStatus()} method).
     */
    public UserEnabledStatusException(String message, int status) {
        super(message, status);
    }
}
