package be.steby.CoreProject.bll.common.exceptions;



public class UserAuthenticationStateException extends CoreProjectException {

    
    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "USER_AUTHENTICATION_STATE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
/**
     * Constructs a new {@code UserAuthenticationStateException} with specified detail message and automatically assign
     * the HTTP status code 401.
     *
     * @param message the detail message to explaining the cause of exception.
     */
    public UserAuthenticationStateException(String message) {
        super(message,400);
    }


    /**
     * Constructs a new {@code AuthenticationException} with the specified {@code detail message} and {@code status code}.
     *
     * @param message the {@code detail message} (which is saved for later retrieval
     *                by the {@link #getMessage()} method).
     * @param status  the {@code HTTP status code} (which is saved for later retrieval
     *                by the {@link #getStatus()} method).
     */
    public UserAuthenticationStateException(String message, int status) {
        super(message, status);
    }
}
