package be.steby.CoreProject.bll.domains.crm.call.exceptions;

/**
 * Exception thrown when a call request fails business validation.
 *
 * <p>Typical causes:</p>
 * <ul>
 *   <li>Neither {@code contactPublicId} nor {@code leadPublicId} provided</li>
 *   <li>A non-terminal status passed to {@code terminate}</li>
 *   <li>Attempting to terminate an already-terminated session</li>
 * </ul>
 *
 * <p>HTTP Status: 400 (Bad Request)</p>
 */
public class CallValidationException extends CallDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CALL_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    public CallValidationException(String message) {
        super(message, 400);
    }
}
