package be.steby.CoreProject.bll.domains.crm.call.exceptions;

/**
 * Exception thrown when a {@link be.steby.CoreProject.dl.entities.crm.CallSession}
 * cannot be found by the given identifier.
 *
 * <p>HTTP Status: 404 (Not Found)</p>
 */
public class CallSessionNotFoundException extends CallDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CALL_SESSION_NOT_FOUND";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    public CallSessionNotFoundException(String message) {
        super(message, 404);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    public static CallSessionNotFoundException byPublicId(String publicId) {
        return new CallSessionNotFoundException("CallSession not found with publicId: " + publicId);
    }

    public static CallSessionNotFoundException byExternalCallId(String externalCallId) {
        return new CallSessionNotFoundException("CallSession not found with externalCallId: " + externalCallId);
    }
}
