package be.steby.CoreProject.bll.domains.crm.call.exceptions;

import be.steby.CoreProject.bll.common.exceptions.CoreProjectException;

/**
 * Base exception for all call domain exceptions.
 *
 * <h3>Exception hierarchy</h3>
 * <pre>
 * CoreProjectException
 * └── CallDomainException
 *     ├── CallSessionNotFoundException
 *     ├── CallAlreadyActiveException
 *     └── CallValidationException
 * </pre>
 *
 * @see CoreProjectException
 */
public abstract class CallDomainException extends CoreProjectException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CALL_DOMAIN";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    public CallDomainException(String message) {
        super(message, 400);
    }

    public CallDomainException(String message, int status) {
        super(message, status);
    }

    public CallDomainException(String message, Throwable cause) {
        super(message, 400, cause);
    }

    public CallDomainException(String message, int status, Throwable cause) {
        super(message, status, cause);
    }
}
