package be.steby.CoreProject.bll.domains.crm.call.exceptions;

/**
 * Exception thrown when a commercial attempts to initiate a call while one is
 * already in progress.
 *
 * <p>The system enforces a single active call per commercial at any time.
 * HTTP Status: 409 (Conflict)</p>
 */
public class CallAlreadyActiveException extends CallDomainException {

    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "CALL_ALREADY_ACTIVE";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────

    public CallAlreadyActiveException(String message) {
        super(message, 409);
    }

    // =========================================================================
    // Static factories
    // =========================================================================

    public static CallAlreadyActiveException forCommercial(String username) {
        return new CallAlreadyActiveException(
                "Commercial '" + username + "' already has an active call session");
    }
}
