package be.steby.CoreProject.bll.domains.account.exceptions;

public class AccountAlreadyActivatedException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ACCOUNT_ALREADY_ACTIVATED";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AccountAlreadyActivatedException(String message) {
        super(message, 409);
    }
}
