package be.steby.CoreProject.bll.domains.account.exceptions;

/**
 * Exception pour les problèmes de confirmation de compte
 */
public class AccountConfirmationException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "ACCOUNT_CONFIRMATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public AccountConfirmationException(String message) {
        super(message); // 400 par défaut
    }

    public AccountConfirmationException(String message, int status) {
        super(message, status);
    }
}