package be.steby.CoreProject.bll.domains.account.exceptions;

/**
 * Exception thrown when signup validation fails.
 * Contains detailed validation errors for client feedback.
 */
public class SignupValidationException extends AccountDomainException {


    // ── auto-generated by add_error_codes.py ──────────────────────
    private static final String ERROR_CODE = "SIGNUP_VALIDATION";

    @Override
    public String getErrorCode() {
        return ERROR_CODE;
    }
    // ────────────────────────────────────────────────────────────────
    public SignupValidationException(String message) {
        super(message);
    }

    public SignupValidationException(String message, Throwable cause) {
        super(message, cause);
    }
}
